/********************************************************************
* ../src/PhyEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/PhyEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePhyEventDict();
extern void G__cpp_setup_inheritancePhyEventDict();
extern void G__cpp_setup_typetablePhyEventDict();
extern void G__cpp_setup_memvarPhyEventDict();
extern void G__cpp_setup_globalPhyEventDict();
extern void G__cpp_setup_memfuncPhyEventDict();
extern void G__cpp_setup_funcPhyEventDict();
extern void G__set_cpp_environmentPhyEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PhyEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PhyEventDictLN_TClass;
extern G__linked_taginfo G__PhyEventDictLN_TBuffer;
extern G__linked_taginfo G__PhyEventDictLN_TMemberInspector;
extern G__linked_taginfo G__PhyEventDictLN_TObject;
extern G__linked_taginfo G__PhyEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PhyEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PhyEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PhyEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PhyEventDictLN_JM;
extern G__linked_taginfo G__PhyEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__PhyEventDictLN_JMcLcLPhyEvent;

/* STUB derived class for protected member access */
