//
// File generated by /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin/rootcint at Thu Dec 28 13:42:06 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIsrcdIPhyHeaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PhyHeaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JMcLcLPhyHeader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JMcLcLPhyHeader(void *p = 0);
   static void *newArray_JMcLcLPhyHeader(Long_t size, void *p);
   static void delete_JMcLcLPhyHeader(void *p);
   static void deleteArray_JMcLcLPhyHeader(void *p);
   static void destruct_JMcLcLPhyHeader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JM::PhyHeader*)
   {
      ::JM::PhyHeader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JM::PhyHeader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JM::PhyHeader", ::JM::PhyHeader::Class_Version(), "./PhyHeader.h", 40,
                  typeid(::JM::PhyHeader), DefineBehavior(ptr, ptr),
                  &::JM::PhyHeader::Dictionary, isa_proxy, 4,
                  sizeof(::JM::PhyHeader) );
      instance.SetNew(&new_JMcLcLPhyHeader);
      instance.SetNewArray(&newArray_JMcLcLPhyHeader);
      instance.SetDelete(&delete_JMcLcLPhyHeader);
      instance.SetDeleteArray(&deleteArray_JMcLcLPhyHeader);
      instance.SetDestructor(&destruct_JMcLcLPhyHeader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JM::PhyHeader*)
   {
      return GenerateInitInstanceLocal((::JM::PhyHeader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JM::PhyHeader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace JM {
//______________________________________________________________________________
TClass *PhyHeader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PhyHeader::Class_Name()
{
   return "JM::PhyHeader";
}

//______________________________________________________________________________
const char *PhyHeader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::PhyHeader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PhyHeader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::PhyHeader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PhyHeader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::PhyHeader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PhyHeader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::PhyHeader*)0x0)->GetClass();
   return fgIsA;
}

} // namespace JM
      namespace JM {
//______________________________________________________________________________
void PhyHeader::Streamer(TBuffer &R__b)
{
   // Stream an object of class JM::PhyHeader.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JM::PhyHeader::Class(),this);
   } else {
      R__b.WriteClassBuffer(JM::PhyHeader::Class(),this);
   }
}

} // namespace JM
//______________________________________________________________________________
      namespace JM {
void PhyHeader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JM::PhyHeader.
      TClass *R__cl = ::JM::PhyHeader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_event", &m_event);
      R__insp.InspectMember(m_event, "m_event.");
      //This works around a msvc bug and should be harmless on other platforms
      typedef JM::HeaderObject baseClass1;
      baseClass1::ShowMembers(R__insp);
}

} // namespace JM
namespace ROOT {
   // Wrappers around operator new
   static void *new_JMcLcLPhyHeader(void *p) {
      return  p ? new(p) ::JM::PhyHeader : new ::JM::PhyHeader;
   }
   static void *newArray_JMcLcLPhyHeader(Long_t nElements, void *p) {
      return p ? new(p) ::JM::PhyHeader[nElements] : new ::JM::PhyHeader[nElements];
   }
   // Wrapper around operator delete
   static void delete_JMcLcLPhyHeader(void *p) {
      delete ((::JM::PhyHeader*)p);
   }
   static void deleteArray_JMcLcLPhyHeader(void *p) {
      delete [] ((::JM::PhyHeader*)p);
   }
   static void destruct_JMcLcLPhyHeader(void *p) {
      typedef ::JM::PhyHeader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JM::PhyHeader

/********************************************************
* ../src/PhyHeaderDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePhyHeaderDict();

extern "C" void G__set_cpp_environmentPhyHeaderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PhyHeader.h");
  G__cpp_reset_tagtablePhyHeaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevPhyHeaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JM::PhyHeader */
static int G__PhyHeaderDict_173_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::PhyHeader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::PhyHeader[n];
     } else {
       p = new((void*) gvp) JM::PhyHeader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::PhyHeader;
     } else {
       p = new((void*) gvp) JM::PhyHeader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::PhyHeader*) G__getstructoffset())->event());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::PhyHeader*) G__getstructoffset())->setEvent((JM::PhyEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JM::PhyHeader*) G__getstructoffset())->hasEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JM::PhyHeader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::PhyHeader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JM::PhyHeader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JM::PhyHeader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::PhyHeader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::PhyHeader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::PhyHeader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::PhyHeader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PhyHeaderDict_173_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::PhyHeader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PhyHeaderDict_173_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JM::PhyHeader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JM::PhyHeader(*(JM::PhyHeader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JM::PhyHeader G__TJMcLcLPhyHeader;
static int G__PhyHeaderDict_173_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JM::PhyHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JM::PhyHeader*) (soff+(sizeof(JM::PhyHeader)*i)))->~G__TJMcLcLPhyHeader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JM::PhyHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JM::PhyHeader*) (soff))->~G__TJMcLcLPhyHeader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PhyHeaderDict_173_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::PhyHeader* dest = (JM::PhyHeader*) G__getstructoffset();
   *dest = *(JM::PhyHeader*) libp->para[0].ref;
   const JM::PhyHeader& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JM::PhyHeader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPhyHeaderDict {
 public:
  G__Sizep2memfuncPhyHeaderDict(): p(&G__Sizep2memfuncPhyHeaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPhyHeaderDict::*p)();
};

size_t G__get_sizep2memfuncPhyHeaderDict()
{
  G__Sizep2memfuncPhyHeaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePhyHeaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader))) {
     JM::PhyHeader *G__Lderived;
     G__Lderived=(JM::PhyHeader*)0x1000;
     {
       JM::HeaderObject *G__Lpbase=(JM::HeaderObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader),G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLHeaderObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       JM::EventObject *G__Lpbase=(JM::EventObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader),G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLEventObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader),G__get_linked_tagnum(&G__PhyHeaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePhyHeaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JM::PhyHeader */
static void G__setup_memvarJMcLcLPhyHeader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader));
   { JM::PhyHeader *p; p=(JM::PhyHeader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLSmartRef),-1,-1,4,"m_event=",0,"||SmartRef to the phyEvent");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PhyHeaderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPhyHeaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJMcLcLPhyHeader(void) {
   /* JM::PhyHeader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader));
   G__memfunc_setup("PhyHeader",890,G__PhyHeaderDict_173_0_1, 105, G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("event",546,G__PhyHeaderDict_173_0_2, 85, G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEvent",846,G__PhyHeaderDict_173_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JM::PhyEvent' - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEventEntry",1376,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - eventName n - 'Long64_t' 1 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("event",546,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLEventObject), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - eventName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("hasEvent",830,G__PhyHeaderDict_173_0_6, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PhyHeaderDict_173_0_7, 85, G__get_linked_tagnum(&G__PhyHeaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JM::PhyHeader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PhyHeaderDict_173_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::PhyHeader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PhyHeaderDict_173_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JM::PhyHeader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PhyHeaderDict_173_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JM::PhyHeader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PhyHeaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PhyHeaderDict_173_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PhyHeaderDict_173_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::PhyHeader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PhyHeaderDict_173_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::PhyHeader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PhyHeaderDict_173_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::PhyHeader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PhyHeaderDict_173_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::PhyHeader::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PhyHeader", 890, G__PhyHeaderDict_173_0_19, (int) ('i'), G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader), -1, 0, 1, 1, 1, 0, "u 'JM::PhyHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PhyHeader", 1016, G__PhyHeaderDict_173_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PhyHeaderDict_173_0_21, (int) ('u'), G__get_linked_tagnum(&G__PhyHeaderDictLN_JMcLcLPhyHeader), -1, 1, 1, 1, 1, 0, "u 'JM::PhyHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPhyHeaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPhyHeaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPhyHeaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PhyHeaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JM = { "JM" , 110 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JMcLcLEventObject = { "JM::EventObject" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JMcLcLHeaderObject = { "JM::HeaderObject" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JMcLcLPhyEvent = { "JM::PhyEvent" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JMcLcLSmartRef = { "JM::SmartRef" , 99 , -1 };
G__linked_taginfo G__PhyHeaderDictLN_JMcLcLPhyHeader = { "JM::PhyHeader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePhyHeaderDict() {
  G__PhyHeaderDictLN_TClass.tagnum = -1 ;
  G__PhyHeaderDictLN_TBuffer.tagnum = -1 ;
  G__PhyHeaderDictLN_TMemberInspector.tagnum = -1 ;
  G__PhyHeaderDictLN_TObject.tagnum = -1 ;
  G__PhyHeaderDictLN_string.tagnum = -1 ;
  G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PhyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PhyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PhyHeaderDictLN_JM.tagnum = -1 ;
  G__PhyHeaderDictLN_JMcLcLEventObject.tagnum = -1 ;
  G__PhyHeaderDictLN_JMcLcLHeaderObject.tagnum = -1 ;
  G__PhyHeaderDictLN_JMcLcLPhyEvent.tagnum = -1 ;
  G__PhyHeaderDictLN_JMcLcLSmartRef.tagnum = -1 ;
  G__PhyHeaderDictLN_JMcLcLPhyHeader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePhyHeaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_string);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JM);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JMcLcLEventObject);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JMcLcLHeaderObject);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JMcLcLPhyEvent);
   G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JMcLcLSmartRef);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PhyHeaderDictLN_JMcLcLPhyHeader),sizeof(JM::PhyHeader),-1,292096,(char*)NULL,G__setup_memvarJMcLcLPhyHeader,G__setup_memfuncJMcLcLPhyHeader);
}
extern "C" void G__cpp_setupPhyHeaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPhyHeaderDict()");
  G__set_cpp_environmentPhyHeaderDict();
  G__cpp_setup_tagtablePhyHeaderDict();

  G__cpp_setup_inheritancePhyHeaderDict();

  G__cpp_setup_typetablePhyHeaderDict();

  G__cpp_setup_memvarPhyHeaderDict();

  G__cpp_setup_memfuncPhyHeaderDict();
  G__cpp_setup_globalPhyHeaderDict();
  G__cpp_setup_funcPhyHeaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPhyHeaderDict();
  return;
}
class G__cpp_setup_initPhyHeaderDict {
  public:
    G__cpp_setup_initPhyHeaderDict() { G__add_setup_func("PhyHeaderDict",(G__incsetup)(&G__cpp_setupPhyHeaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPhyHeaderDict() { G__remove_setup_func("PhyHeaderDict"); }
};
G__cpp_setup_initPhyHeaderDict G__cpp_setup_initializerPhyHeaderDict;

