#!/usr/bin/python
# -*- coding:utf-8 -*-
#
# Author: Jilei Xu - xujl@ihep.ac.cn
# Last modified:	2016-11-13 01:40
# Filename:		test.py
# Description:  reference RecCdMuonAlg

import Sniper
Sniper.setLogLevel(1)
task = Sniper.Task("task")
task.asTop()
task.setLogLevel(1)

import BufferMemMgr
bufMgr = task.createSvc("BufferMemMgr")
bufMgr.property("TimeWindow").set([0, 0]);

import DataRegistritionSvc
task.property("svcs").append("DataRegistritionSvc")

import RootIOSvc
roSvc = task.createSvc("RootOutputSvc/OutputSvc")
roSvc.property("OutputStreams").set({"/Event/RecTrack": "recOut.root", "/Event/Calib":"recOut.root"})
riSvc = task.createSvc("RootInputSvc/InputSvc")
riSvc.property("InputFile").set(["general_60000.root", "general_60001.root"]) #input your sim root file

import Geometry
geom = task.createSvc("RecGeomSvc")
gdmlgeo = "./geom.root" # here can input any general.root if it was  generated by command --gdml when sim.
geom.property("GeomFile").set(gdmlgeo)
geom.property("FastInit").set(True)

Sniper.loadDll("libPmtRec.so")
task.property("algs").append("PullSimHeaderAlg")

import RecWpMuonAlg
recalg = RecWpMuonAlg.createAlg(task)
recalg.setLogLevel(1)
recalg.useRecTool("RecDummyWpTool")


task.setEvtMax(-1)
task.show()
task.run()
