/********************************************************************
* ../src/TimeStampDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/TimeStampDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTimeStampDict();
extern void G__cpp_setup_inheritanceTimeStampDict();
extern void G__cpp_setup_typetableTimeStampDict();
extern void G__cpp_setup_memvarTimeStampDict();
extern void G__cpp_setup_globalTimeStampDict();
extern void G__cpp_setup_memfuncTimeStampDict();
extern void G__cpp_setup_funcTimeStampDict();
extern void G__set_cpp_environmentTimeStampDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TimeStamp.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TimeStampDictLN_tm;
extern G__linked_taginfo G__TimeStampDictLN_TClass;
extern G__linked_taginfo G__TimeStampDictLN_TBuffer;
extern G__linked_taginfo G__TimeStampDictLN_TMemberInspector;
extern G__linked_taginfo G__TimeStampDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TimeStampDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TimeStampDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TimeStampDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TimeStampDictLN_timespec;
extern G__linked_taginfo G__TimeStampDictLN_TimeStamp;

/* STUB derived class for protected member access */
