----------> uses
# use Tutorial v* Examples (no_version_directory)
#   use DataModelRelease v* DataModel (no_version_directory)
#     use BaseEvent v* DataModel (no_version_directory)
#       use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#         use SniperPolicy v*  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#     use GenEventV2 v* DataModel (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#         use BaseEvent v* DataModel (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#           use SniperPolicy v*  (no_version_directory)
#           use Boost v* Externals (no_version_directory)
#             use Python v* Externals (no_version_directory)
#       use HepMC v* Externals (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#       use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#         use SniperPolicy v*  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#       use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#       use CLHEPDict v* DataModel/Dict (no_version_directory)
#         use SniperPolicy *  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#         use CLHEP v* Externals (no_version_directory)
#         use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#       use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use PhyEvent v* DataModel (no_version_directory)
#       use XmlObjDesc v*  (no_auto_imports) (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#     use EDMUtil v* DataModel (no_version_directory)
#   use BufferMemMgr v* CommonSvc (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use RootIOUtil v* RootIO (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use BaseEvent v* DataModel (no_version_directory)
#         use EDMUtil v* DataModel (no_version_directory)
#         use EvtNavigator v* DataModel (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#   use RandomSvc v* CommonSvc (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use CLHEP v* Externals (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#   use JobInfoSvc v* CommonSvc (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use EDMUtil v* DataModel (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#   use RootIORelease v* RootIO (no_version_directory)
#     use RootIOUtil v* RootIO (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#     use RootIOTest v* RootIO (no_version_directory)
#       use RootIOSvc v* RootIO (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use BaseEvent v* DataModel (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use RecEvent v* DataModel (no_version_directory)
#       use JunoTest v* Validation (no_version_directory)
#         use SniperPolicy v*  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#     use RootIOTools v* RootIO (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use DataModelRelease v* DataModel (no_version_directory)
#       use RootIOSvc v* RootIO (no_version_directory)
#       use RootIOUtil v* RootIO (no_version_directory)
#       use EDMUtil v* DataModel (no_version_directory)
#   use GeneratorRelease v* Generator (no_version_directory)
#     use InverseBeta v* Generator (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Muon v* Generator (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use K40 v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Co60 v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Ge68 v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Cf252 v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use AmC v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use AmBe v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Cs137 v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use PuC v* Generator/RadioActivity (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#     use Supernova v* Generator (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#     use NuSolGen v* Generator (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Geant4 v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#       use HepMC v* Externals (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use GenTools v* Simulation (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use RootWriter v* SniperSvc (no_version_directory)
#           use SniperKernel v*  (no_version_directory)
#           use ROOT v* Externals (no_version_directory)
#           use Boost v* Externals (no_version_directory)
#         use Boost v* Externals (no_version_directory)
#         use HepMC v* Externals (no_version_directory)
#         use CLHEP v* Externals (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#         use Geant4 v* Externals (no_version_directory)
#         use RandomSvc v* CommonSvc (no_version_directory)
#         use MCGlobalTimeSvc v* Simulation/DetSimV2 (no_version_directory)
#           use SniperKernel v*  (no_version_directory)
#           use ROOT v* Externals (no_version_directory)
#           use CLHEP v* Externals (no_version_directory)
#         use EvtNavigator v* DataModel (no_version_directory)
#         use GenEventV2 v* DataModel (no_version_directory)
#     use DSNB v* Generator (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#   use GenTools v* Simulation (no_version_directory)
#   use GenDecay v* Simulation (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use GenTools v* Simulation (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use HepMC v* Externals (no_version_directory)
#     use CLHEP v* Externals (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use More v* Externals (no_version_directory)
#     use RandomSvc v* CommonSvc (no_version_directory)
#   use DetSimOptions v* Simulation/DetSimV2 (no_version_directory)
#     use SniperRelease v*  (no_version_directory)
#       use SniperPolicy v*  (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use DataBuffer v* SniperUtil (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#       use HelloWorld v* Examples (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#       use RootWriter v* SniperSvc (no_version_directory)
#       use DummyAlg v* Examples (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use RootWriter v* SniperSvc (no_version_directory)
#     use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use Geant4 v* Externals (no_version_directory)
#       use CLHEP v* Externals (no_version_directory)
#       use Xercesc v* Externals (no_version_directory)
#     use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use G4Svc v* Simulation/DetSimV2 (no_version_directory)
#         use SniperPolicy v*  (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#     use PhysiSim v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#     use PMTSim v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use SimUtil v* Simulation/DetSimV2 (no_version_directory)
#         use SniperRelease v*  (no_version_directory)
#         use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#         use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#       use GenSim v* Simulation/DetSimV2 (no_version_directory)
#         use SniperRelease v*  (no_version_directory)
#         use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#     use GenSim v* Simulation/DetSimV2 (no_version_directory)
#     use SimUtil v* Simulation/DetSimV2 (no_version_directory)
#     use MCParamsSvc v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#     use CentralDetector v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#       use Geometry v* Detector (no_version_directory)
#         use Identifier v* Detector (no_version_directory)
#           use SniperKernel v*  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#     use AnalysisCode v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#       use PMTSim v* Simulation/DetSimV2 (no_version_directory)
#       use SimUtil v* Simulation/DetSimV2 (no_version_directory)
#       use DAE v* Simulation/DetSimV2 (no_version_directory)
#         use SniperPolicy v*  (no_version_directory)
#         use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use GenTools v* Simulation (no_version_directory)
#       use JunoTimer v* Utilities (no_version_directory)
#         use SniperRelease v*  (no_version_directory)
#         use Boost v* Externals (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use RootIOSvc v* RootIO (no_version_directory)
#       use Geometry v* Detector (no_version_directory)
#     use TopTracker v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#     use CalibUnit v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#     use Chimney v* Simulation/DetSimV2 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#       use DetSimPolicy v* Simulation/DetSimV2 (no_version_directory)
#       use DetSimAlg v* Simulation/DetSimV2 (no_version_directory)
#     use GenTools v* Simulation (no_version_directory)
#   use ElecSim v* Simulation (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use ReadOutAlg v* Simulation/ElecSimV3 (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#     use Context v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use InputReviser v* Utilities (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use RootIOSvc v* RootIO (no_version_directory)
#     use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#     use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#     use ElecBufferMgrSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use Context v* DataModel (no_version_directory)
#         use ElecEvent v* DataModel (no_version_directory)
#         use SimEventV2 v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#     use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#     use PreTrgAlg v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use InputReviser v* Utilities (no_version_directory)
#       use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecBufferMgrSvc v* Simulation/ElecSimV3 (no_version_directory)
#     use WaveformSimAlg v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use InputReviser v* Utilities (no_version_directory)
#       use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecBufferMgrSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperRelease v*  (no_version_directory)
#     use EvtMixingAlg v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use InputReviser v* Utilities (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#       use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#     use PMTSimAlg v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use InputReviser v* Utilities (no_version_directory)
#       use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#       use PmtParamSvc v* Simulation/ElecSimV3 (no_version_directory)
#         use SniperKernel v*  (no_version_directory)
#         use ROOT v* Externals (no_version_directory)
#         use Context v* DataModel (no_version_directory)
#       use ElecBufferMgrSvc v* Simulation/ElecSimV3 (no_version_directory)
#     use UnpackingAlg v* Simulation/ElecSimV3 (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#       use Boost v* Externals (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use ElecEvent v* DataModel (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use BufferMemMgr v* CommonSvc (no_version_directory)
#       use Context v* DataModel (no_version_directory)
#       use DataRegistritionSvc v* DataModel (no_version_directory)
#       use InputReviser v* Utilities (no_version_directory)
#       use RootRandomSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use GlobalTimeSvc v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecDataStruct v* Simulation/ElecSimV3 (no_version_directory)
#       use ElecBufferMgrSvc v* Simulation/ElecSimV3 (no_version_directory)
#     use PmtParamSvc v* Simulation/ElecSimV3 (no_version_directory)
#   use PmtRec v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use RandomSvc v* CommonSvc (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use WaveFitAlg v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use RecTimeLikeAlg v* Reconstruction (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#   use OMILREC v* Reconstruction (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SniperRelease v*  (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#   use IntegralPmtRec v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use RecCdMuonAlg v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use CLHEP v* Externals (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#     use RootWriter v* SniperSvc (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use LsqMuonRecTool v* Reconstruction (no_version_directory)
#     use RecCdMuonAlg v* Reconstruction (no_version_directory)
#   use PushAndPull v* Reconstruction (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#   use Deconvolution v* Reconstruction (no_version_directory)
#     use SniperRelease v*  (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#   use MuonWaveRec v* Reconstruction (no_version_directory)
#     use SniperRelease v*  (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#   use SpmtMuonRecTool v* Reconstruction (no_version_directory)
#     use RecCdMuonAlg v* Reconstruction (no_version_directory)
#   use RecWpMuonAlg v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use CLHEP v* Externals (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#     use RootWriter v* SniperSvc (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#   use PoolMuonRecTool v* Reconstruction (no_version_directory)
#     use RecWpMuonAlg v* Reconstruction (no_version_directory)
#   use ConeMuonRecTool v* Reconstruction (no_version_directory)
#     use RecCdMuonAlg v* Reconstruction (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#   use TTCalib v* Reconstruction (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#     use RootWriter v* SniperSvc (no_version_directory)
#   use TTTracking v* Reconstruction (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use SimEventV2 v* DataModel (no_version_directory)
#     use RecEvent v* DataModel (no_version_directory)
#     use CalibEvent v* DataModel (no_version_directory)
#     use Identifier v* Detector (no_version_directory)
#     use Geometry v* Detector (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use BufferMemMgr v* CommonSvc (no_version_directory)
#     use RootIOSvc v* RootIO (no_version_directory)
#     use RootWriter v* SniperSvc (no_version_directory)
#   use PMTCalib v* Calibration (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use Boost v* Externals (no_version_directory)
#     use RootWriter v* SniperSvc (no_version_directory)
#     use EvtNavigator v* DataModel (no_version_directory)
#     use DataRegistritionSvc v* DataModel (no_version_directory)
#     use ElecEvent v* DataModel (no_version_directory)
#   use VisClient v* EventDisplay (no_version_directory)
#     use SniperKernel v*  (no_version_directory)
#     use ROOT v* Externals (no_version_directory)
#     use JVisLib v* EventDisplay (no_version_directory)
#       use SniperKernel v*  (no_version_directory)
#       use EvtNavigator v* DataModel (no_version_directory)
#       use SimEventV2 v* DataModel (no_version_directory)
#       use CalibEvent v* DataModel (no_version_directory)
#       use RecEvent v* DataModel (no_version_directory)
#       use CLHEPDict v* DataModel/Dict (no_version_directory)
#       use Identifier v* Detector (no_version_directory)
#       use Geometry v* Detector (no_version_directory)
#       use ROOT v* Externals (no_version_directory)
#   use JunoTest v* Validation (no_version_directory)
#
# Selection :
use CMT v1r26 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs)
use Xercesc v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use More v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use Geant4 v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use CLHEP v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use DetSimPolicy v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use HepMC v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use Python v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use Boost v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use ROOT v0 Externals (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface)
use DSNB v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Supernova v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PuC v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Cs137 v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use AmBe v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use AmC v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Cf252 v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Ge68 v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Co60 v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use K40 v0 Generator/RadioActivity (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Muon v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use InverseBeta v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use SniperPolicy v0  (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use DAE v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use JunoTest v0 Validation (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Context v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use SniperKernel v2  (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use PmtParamSvc v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GlobalTimeSvc v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootRandomSvc v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Identifier v0 Detector (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Geometry v0 Detector (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use G4Svc v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use HelloWorld v1 Examples (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use DataBuffer v0 SniperUtil (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use MCGlobalTimeSvc v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootWriter v0 SniperSvc (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use DummyAlg v0 Examples (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use SniperRelease v2  (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper)
use JunoTimer v0 Utilities (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use MCParamsSvc v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GenSim v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PhysiSim v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use DetSimAlg v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Chimney v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use CalibUnit v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use TopTracker v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use CentralDetector v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use SimUtil v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PMTSim v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RandomSvc v0 CommonSvc (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use XmlObjDesc v0  (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline) (no_auto_imports)
use CLHEPDict v0 DataModel/Dict (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use BaseEvent v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use EDMUtil v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use DataRegistritionSvc v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use EvtNavigator v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootIOUtil v0 RootIO (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootIOSvc v0 RootIO (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use JobInfoSvc v0 CommonSvc (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use BufferMemMgr v0 CommonSvc (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use InputReviser v0 Utilities (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PhyEvent v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use CalibEvent v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RecEvent v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RecWpMuonAlg v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PoolMuonRecTool v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RecCdMuonAlg v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use SpmtMuonRecTool v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use LsqMuonRecTool v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use OMILREC v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RecTimeLikeAlg v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ElecEvent v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PMTCalib v0 Calibration (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use MuonWaveRec v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Deconvolution v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use IntegralPmtRec v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use WaveFitAlg v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use SimEventV2 v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use JVisLib v0 EventDisplay (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use VisClient v0 EventDisplay (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use TTTracking v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use TTCalib v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ConeMuonRecTool v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PushAndPull ./ Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PmtRec v0 Reconstruction (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ElecDataStruct v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use EvtMixingAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ElecBufferMgrSvc v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use UnpackingAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PMTSimAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use WaveformSimAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use PreTrgAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ReadOutAlg v0 Simulation/ElecSimV3 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use ElecSim v0 Simulation (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootIOTest v0 RootIO (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GenEventV2 v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GenTools v0 Simulation (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use AnalysisCode v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use DetSimOptions v0 Simulation/DetSimV2 (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GenDecay v0 Simulation (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use NuSolGen v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use GeneratorRelease v0 Generator (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use DataModelRelease v0 DataModel (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootIOTools v0 RootIO (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use RootIORelease v0 RootIO (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
use Tutorial v0 Examples (/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline)
----------> tags
CMTv1 (from CMTVERSION)
CMTr26 (from CMTVERSION)
CMTp0 (from CMTVERSION)
Linux (from uname) package [CMT] implies [Unix]
amd64_linux26 (from CMTCONFIG)
offline_no_config (from PROJECT) excludes [offline_config]
offline_root (from PROJECT) excludes [offline_no_root]
offline_cleanup (from PROJECT) excludes [offline_no_cleanup]
offline_scripts (from PROJECT) excludes [offline_no_scripts]
offline_prototypes (from PROJECT) excludes [offline_no_prototypes]
offline_with_installarea (from PROJECT) excludes [offline_without_installarea]
offline_without_version_directory (from PROJECT) excludes [offline_with_version_directory]
sniper_no_config (from PROJECT) excludes [sniper_config]
sniper_root (from PROJECT) excludes [sniper_no_root]
sniper_cleanup (from PROJECT) excludes [sniper_no_cleanup]
sniper_scripts (from PROJECT) excludes [sniper_no_scripts]
sniper_prototypes (from PROJECT) excludes [sniper_no_prototypes]
sniper_with_installarea (from PROJECT) excludes [sniper_without_installarea]
sniper_without_version_directory (from PROJECT) excludes [sniper_with_version_directory]
ExternalInterface_no_config (from PROJECT) excludes [ExternalInterface_config]
ExternalInterface_no_root (from PROJECT) excludes [ExternalInterface_root]
ExternalInterface_cleanup (from PROJECT) excludes [ExternalInterface_no_cleanup]
ExternalInterface_scripts (from PROJECT) excludes [ExternalInterface_no_scripts]
ExternalInterface_prototypes (from PROJECT) excludes [ExternalInterface_no_prototypes]
ExternalInterface_without_installarea (from PROJECT) excludes [ExternalInterface_with_installarea]
ExternalInterface_without_version_directory (from PROJECT) excludes [ExternalInterface_with_version_directory]
offline (from PROJECT)
x86_64 (from package CMT)
sl69 (from package CMT)
gcc447 (from package CMT)
Unix (from package CMT) excludes [WIN32 Win32]
----------> CMTPATH
# Add path /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/offline from initialization
# Add path /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper from ProjectPath
# Add path /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface from ProjectPath
