/********************************************************************
* ../src/SimEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SimEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimEventDict();
extern void G__cpp_setup_inheritanceSimEventDict();
extern void G__cpp_setup_typetableSimEventDict();
extern void G__cpp_setup_memvarSimEventDict();
extern void G__cpp_setup_globalSimEventDict();
extern void G__cpp_setup_memfuncSimEventDict();
extern void G__cpp_setup_funcSimEventDict();
extern void G__set_cpp_environmentSimEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SimEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimEventDictLN_TClass;
extern G__linked_taginfo G__SimEventDictLN_TBuffer;
extern G__linked_taginfo G__SimEventDictLN_TMemberInspector;
extern G__linked_taginfo G__SimEventDictLN_TObject;
extern G__linked_taginfo G__SimEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimEventDictLN_JM;
extern G__linked_taginfo G__SimEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__SimEventDictLN_JMcLcLSimPMTHit;
extern G__linked_taginfo G__SimEventDictLN_JMcLcLSimTTHit;
extern G__linked_taginfo G__SimEventDictLN_JMcLcLSimTrack;
extern G__linked_taginfo G__SimEventDictLN_JMcLcLSimEvent;
extern G__linked_taginfo G__SimEventDictLN_vectorlEJMcLcLSimTrackmUcOallocatorlEJMcLcLSimTrackmUgRsPgR;
extern G__linked_taginfo G__SimEventDictLN_reverse_iteratorlEvectorlEJMcLcLSimTrackmUcOallocatorlEJMcLcLSimTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimEventDictLN_vectorlEJMcLcLSimPMTHitmUcOallocatorlEJMcLcLSimPMTHitmUgRsPgR;
extern G__linked_taginfo G__SimEventDictLN_reverse_iteratorlEvectorlEJMcLcLSimPMTHitmUcOallocatorlEJMcLcLSimPMTHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimEventDictLN_vectorlEJMcLcLSimTTHitmUcOallocatorlEJMcLcLSimTTHitmUgRsPgR;
extern G__linked_taginfo G__SimEventDictLN_reverse_iteratorlEvectorlEJMcLcLSimTTHitmUcOallocatorlEJMcLcLSimTTHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
