/********************************************************************
* ../src/SimHeaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SimHeaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimHeaderDict();
extern void G__cpp_setup_inheritanceSimHeaderDict();
extern void G__cpp_setup_typetableSimHeaderDict();
extern void G__cpp_setup_memvarSimHeaderDict();
extern void G__cpp_setup_globalSimHeaderDict();
extern void G__cpp_setup_memfuncSimHeaderDict();
extern void G__cpp_setup_funcSimHeaderDict();
extern void G__set_cpp_environmentSimHeaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SimHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimHeaderDictLN_TClass;
extern G__linked_taginfo G__SimHeaderDictLN_TBuffer;
extern G__linked_taginfo G__SimHeaderDictLN_TMemberInspector;
extern G__linked_taginfo G__SimHeaderDictLN_TObject;
extern G__linked_taginfo G__SimHeaderDictLN_string;
extern G__linked_taginfo G__SimHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimHeaderDictLN_JM;
extern G__linked_taginfo G__SimHeaderDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__SimHeaderDictLN_JMcLcLHeaderObject;
extern G__linked_taginfo G__SimHeaderDictLN_JMcLcLSmartRef;
extern G__linked_taginfo G__SimHeaderDictLN_JMcLcLSimEvent;
extern G__linked_taginfo G__SimHeaderDictLN_vectorlEJMcLcLSimTrackmUcOallocatorlEJMcLcLSimTrackmUgRsPgR;
extern G__linked_taginfo G__SimHeaderDictLN_reverse_iteratorlEvectorlEJMcLcLSimTrackmUcOallocatorlEJMcLcLSimTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimHeaderDictLN_vectorlEJMcLcLSimPMTHitmUcOallocatorlEJMcLcLSimPMTHitmUgRsPgR;
extern G__linked_taginfo G__SimHeaderDictLN_reverse_iteratorlEvectorlEJMcLcLSimPMTHitmUcOallocatorlEJMcLcLSimPMTHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimHeaderDictLN_vectorlEJMcLcLSimTTHitmUcOallocatorlEJMcLcLSimTTHitmUgRsPgR;
extern G__linked_taginfo G__SimHeaderDictLN_reverse_iteratorlEvectorlEJMcLcLSimTTHitmUcOallocatorlEJMcLcLSimTTHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimHeaderDictLN_JMcLcLSimHeader;

/* STUB derived class for protected member access */
