/********************************************************************
* ../src/SimTrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SimTrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimTrackDict();
extern void G__cpp_setup_inheritanceSimTrackDict();
extern void G__cpp_setup_typetableSimTrackDict();
extern void G__cpp_setup_memvarSimTrackDict();
extern void G__cpp_setup_globalSimTrackDict();
extern void G__cpp_setup_memfuncSimTrackDict();
extern void G__cpp_setup_funcSimTrackDict();
extern void G__set_cpp_environmentSimTrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SimTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimTrackDictLN_TClass;
extern G__linked_taginfo G__SimTrackDictLN_TBuffer;
extern G__linked_taginfo G__SimTrackDictLN_TMemberInspector;
extern G__linked_taginfo G__SimTrackDictLN_TObject;
extern G__linked_taginfo G__SimTrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimTrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimTrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimTrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimTrackDictLN_JM;
extern G__linked_taginfo G__SimTrackDictLN_JMcLcLSimTrack;
extern G__linked_taginfo G__SimTrackDictLN_vectorlEJMcLcLSimTrackcOallocatorlEJMcLcLSimTrackgRsPgR;
extern G__linked_taginfo G__SimTrackDictLN_vectorlEJMcLcLSimTrackcOallocatorlEJMcLcLSimTrackgRsPgRcLcLiterator;
extern G__linked_taginfo G__SimTrackDictLN_reverse_iteratorlEvectorlEJMcLcLSimTrackcOallocatorlEJMcLcLSimTrackgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<JM::SimTrack,allocator<JM::SimTrack> > G__vectorlEJMcLcLSimTrackcOallocatorlEJMcLcLSimTrackgRsPgR;
