/********************************************************************
* ../src/CDRecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/CDRecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCDRecEventDict();
extern void G__cpp_setup_inheritanceCDRecEventDict();
extern void G__cpp_setup_typetableCDRecEventDict();
extern void G__cpp_setup_memvarCDRecEventDict();
extern void G__cpp_setup_globalCDRecEventDict();
extern void G__cpp_setup_memfuncCDRecEventDict();
extern void G__cpp_setup_funcCDRecEventDict();
extern void G__set_cpp_environmentCDRecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CDRecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDRecEventDictLN_TClass;
extern G__linked_taginfo G__CDRecEventDictLN_TBuffer;
extern G__linked_taginfo G__CDRecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__CDRecEventDictLN_TObject;
extern G__linked_taginfo G__CDRecEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__CDRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDRecEventDictLN_JM;
extern G__linked_taginfo G__CDRecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__CDRecEventDictLN_JMcLcLCDRecEvent;

/* STUB derived class for protected member access */
