/********************************************************************
* ../src/CDTrackRecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/CDTrackRecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCDTrackRecEventDict();
extern void G__cpp_setup_inheritanceCDTrackRecEventDict();
extern void G__cpp_setup_typetableCDTrackRecEventDict();
extern void G__cpp_setup_memvarCDTrackRecEventDict();
extern void G__cpp_setup_globalCDTrackRecEventDict();
extern void G__cpp_setup_memfuncCDTrackRecEventDict();
extern void G__cpp_setup_funcCDTrackRecEventDict();
extern void G__set_cpp_environmentCDTrackRecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CDTrackRecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CDTrackRecEventDictLN_TClass;
extern G__linked_taginfo G__CDTrackRecEventDictLN_TBuffer;
extern G__linked_taginfo G__CDTrackRecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__CDTrackRecEventDictLN_TObject;
extern G__linked_taginfo G__CDTrackRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CDTrackRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDTrackRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CDTrackRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CDTrackRecEventDictLN_JM;
extern G__linked_taginfo G__CDTrackRecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__CDTrackRecEventDictLN_JMcLcLRecTrack;
extern G__linked_taginfo G__CDTrackRecEventDictLN_JMcLcLCDTrackRecEvent;
extern G__linked_taginfo G__CDTrackRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR;
extern G__linked_taginfo G__CDTrackRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
