/********************************************************************
* ../src/RecHeaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/RecHeaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRecHeaderDict();
extern void G__cpp_setup_inheritanceRecHeaderDict();
extern void G__cpp_setup_typetableRecHeaderDict();
extern void G__cpp_setup_memvarRecHeaderDict();
extern void G__cpp_setup_globalRecHeaderDict();
extern void G__cpp_setup_memfuncRecHeaderDict();
extern void G__cpp_setup_funcRecHeaderDict();
extern void G__set_cpp_environmentRecHeaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RecHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RecHeaderDictLN_TClass;
extern G__linked_taginfo G__RecHeaderDictLN_TBuffer;
extern G__linked_taginfo G__RecHeaderDictLN_TMemberInspector;
extern G__linked_taginfo G__RecHeaderDictLN_TObject;
extern G__linked_taginfo G__RecHeaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__RecHeaderDictLN_string;
extern G__linked_taginfo G__RecHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RecHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RecHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecHeaderDictLN_JM;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLHeaderObject;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLCDRecEvent;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLCDTrackRecEvent;
extern G__linked_taginfo G__RecHeaderDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR;
extern G__linked_taginfo G__RecHeaderDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLWPRecEvent;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLTTRecEvent;
extern G__linked_taginfo G__RecHeaderDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__RecHeaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLSmartRef;
extern G__linked_taginfo G__RecHeaderDictLN_JMcLcLRecHeader;

/* STUB derived class for protected member access */
