/********************************************************************
* ../src/RecTrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/RecTrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRecTrackDict();
extern void G__cpp_setup_inheritanceRecTrackDict();
extern void G__cpp_setup_typetableRecTrackDict();
extern void G__cpp_setup_memvarRecTrackDict();
extern void G__cpp_setup_globalRecTrackDict();
extern void G__cpp_setup_memfuncRecTrackDict();
extern void G__cpp_setup_funcRecTrackDict();
extern void G__set_cpp_environmentRecTrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RecTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RecTrackDictLN_TClass;
extern G__linked_taginfo G__RecTrackDictLN_TBuffer;
extern G__linked_taginfo G__RecTrackDictLN_TMemberInspector;
extern G__linked_taginfo G__RecTrackDictLN_TObject;
extern G__linked_taginfo G__RecTrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RecTrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecTrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RecTrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RecTrackDictLN_CLHEP;
extern G__linked_taginfo G__RecTrackDictLN_CLHEPcLcLHepLorentzVector;
extern G__linked_taginfo G__RecTrackDictLN_JM;
extern G__linked_taginfo G__RecTrackDictLN_JMcLcLRecTrack;

/* STUB derived class for protected member access */
