/********************************************************************
* ../src/TTRecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/TTRecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTRecEventDict();
extern void G__cpp_setup_inheritanceTTRecEventDict();
extern void G__cpp_setup_typetableTTRecEventDict();
extern void G__cpp_setup_memvarTTRecEventDict();
extern void G__cpp_setup_globalTTRecEventDict();
extern void G__cpp_setup_memfuncTTRecEventDict();
extern void G__cpp_setup_funcTTRecEventDict();
extern void G__set_cpp_environmentTTRecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTRecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTRecEventDictLN_TClass;
extern G__linked_taginfo G__TTRecEventDictLN_TBuffer;
extern G__linked_taginfo G__TTRecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__TTRecEventDictLN_TObject;
extern G__linked_taginfo G__TTRecEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TTRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTRecEventDictLN_JM;
extern G__linked_taginfo G__TTRecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__TTRecEventDictLN_JMcLcLTTRecEvent;
extern G__linked_taginfo G__TTRecEventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTRecEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
