//
// File generated by /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin/rootcint at Thu Dec 28 13:42:27 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIsrcdIWPRecEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "WPRecEventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JMcLcLWPRecEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JMcLcLWPRecEvent(void *p = 0);
   static void *newArray_JMcLcLWPRecEvent(Long_t size, void *p);
   static void delete_JMcLcLWPRecEvent(void *p);
   static void deleteArray_JMcLcLWPRecEvent(void *p);
   static void destruct_JMcLcLWPRecEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JM::WPRecEvent*)
   {
      ::JM::WPRecEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JM::WPRecEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JM::WPRecEvent", ::JM::WPRecEvent::Class_Version(), "./WPRecEvent.h", 39,
                  typeid(::JM::WPRecEvent), DefineBehavior(ptr, ptr),
                  &::JM::WPRecEvent::Dictionary, isa_proxy, 4,
                  sizeof(::JM::WPRecEvent) );
      instance.SetNew(&new_JMcLcLWPRecEvent);
      instance.SetNewArray(&newArray_JMcLcLWPRecEvent);
      instance.SetDelete(&delete_JMcLcLWPRecEvent);
      instance.SetDeleteArray(&deleteArray_JMcLcLWPRecEvent);
      instance.SetDestructor(&destruct_JMcLcLWPRecEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JM::WPRecEvent*)
   {
      return GenerateInitInstanceLocal((::JM::WPRecEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JM::WPRecEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace JM {
//______________________________________________________________________________
TClass *WPRecEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *WPRecEvent::Class_Name()
{
   return "JM::WPRecEvent";
}

//______________________________________________________________________________
const char *WPRecEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::WPRecEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int WPRecEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::WPRecEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void WPRecEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::WPRecEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *WPRecEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::WPRecEvent*)0x0)->GetClass();
   return fgIsA;
}

} // namespace JM
      namespace JM {
//______________________________________________________________________________
void WPRecEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class JM::WPRecEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JM::WPRecEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(JM::WPRecEvent::Class(),this);
   }
}

} // namespace JM
//______________________________________________________________________________
      namespace JM {
void WPRecEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JM::WPRecEvent.
      TClass *R__cl = ::JM::WPRecEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_wpTracks", (void*)&m_wpTracks);
      R__insp.InspectMember("vector<JM::RecTrack*>", (void*)&m_wpTracks, "m_wpTracks.", false);
      //This works around a msvc bug and should be harmless on other platforms
      typedef JM::EventObject baseClass1;
      baseClass1::ShowMembers(R__insp);
}

} // namespace JM
namespace ROOT {
   // Wrappers around operator new
   static void *new_JMcLcLWPRecEvent(void *p) {
      return  p ? new(p) ::JM::WPRecEvent : new ::JM::WPRecEvent;
   }
   static void *newArray_JMcLcLWPRecEvent(Long_t nElements, void *p) {
      return p ? new(p) ::JM::WPRecEvent[nElements] : new ::JM::WPRecEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_JMcLcLWPRecEvent(void *p) {
      delete ((::JM::WPRecEvent*)p);
   }
   static void deleteArray_JMcLcLWPRecEvent(void *p) {
      delete [] ((::JM::WPRecEvent*)p);
   }
   static void destruct_JMcLcLWPRecEvent(void *p) {
      typedef ::JM::WPRecEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JM::WPRecEvent

namespace ROOT {
   void vectorlEJMcLcLRecTrackmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEJMcLcLRecTrackmUgR_Dictionary();
   static void *new_vectorlEJMcLcLRecTrackmUgR(void *p = 0);
   static void *newArray_vectorlEJMcLcLRecTrackmUgR(Long_t size, void *p);
   static void delete_vectorlEJMcLcLRecTrackmUgR(void *p);
   static void deleteArray_vectorlEJMcLcLRecTrackmUgR(void *p);
   static void destruct_vectorlEJMcLcLRecTrackmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<JM::RecTrack*>*)
   {
      vector<JM::RecTrack*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<JM::RecTrack*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<JM::RecTrack*>", -2, "prec_stl/vector", 49,
                  typeid(vector<JM::RecTrack*>), DefineBehavior(ptr, ptr),
                  0, &vectorlEJMcLcLRecTrackmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<JM::RecTrack*>) );
      instance.SetNew(&new_vectorlEJMcLcLRecTrackmUgR);
      instance.SetNewArray(&newArray_vectorlEJMcLcLRecTrackmUgR);
      instance.SetDelete(&delete_vectorlEJMcLcLRecTrackmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEJMcLcLRecTrackmUgR);
      instance.SetDestructor(&destruct_vectorlEJMcLcLRecTrackmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<JM::RecTrack*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<JM::RecTrack*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEJMcLcLRecTrackmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<JM::RecTrack*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEJMcLcLRecTrackmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JM::RecTrack*> : new vector<JM::RecTrack*>;
   }
   static void *newArray_vectorlEJMcLcLRecTrackmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<JM::RecTrack*>[nElements] : new vector<JM::RecTrack*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEJMcLcLRecTrackmUgR(void *p) {
      delete ((vector<JM::RecTrack*>*)p);
   }
   static void deleteArray_vectorlEJMcLcLRecTrackmUgR(void *p) {
      delete [] ((vector<JM::RecTrack*>*)p);
   }
   static void destruct_vectorlEJMcLcLRecTrackmUgR(void *p) {
      typedef vector<JM::RecTrack*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<JM::RecTrack*>

/********************************************************
* ../src/WPRecEventDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableWPRecEventDict();

extern "C" void G__set_cpp_environmentWPRecEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("WPRecEvent.h");
  G__cpp_reset_tagtableWPRecEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevWPRecEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JM::WPRecEvent */
static int G__WPRecEventDict_205_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::WPRecEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::WPRecEvent[n];
     } else {
       p = new((void*) gvp) JM::WPRecEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::WPRecEvent;
     } else {
       p = new((void*) gvp) JM::WPRecEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const JM::WPRecEvent*) G__getstructoffset())->getTrack((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::WPRecEvent*) G__getstructoffset())->addTrack((JM::RecTrack*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<JM::RecTrack*>& obj = ((const JM::WPRecEvent*) G__getstructoffset())->wpTracks();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JM::WPRecEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::WPRecEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JM::WPRecEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JM::WPRecEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::WPRecEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::WPRecEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::WPRecEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::WPRecEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WPRecEventDict_205_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::WPRecEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__WPRecEventDict_205_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JM::WPRecEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JM::WPRecEvent(*(JM::WPRecEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JM::WPRecEvent G__TJMcLcLWPRecEvent;
static int G__WPRecEventDict_205_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JM::WPRecEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JM::WPRecEvent*) (soff+(sizeof(JM::WPRecEvent)*i)))->~G__TJMcLcLWPRecEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JM::WPRecEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JM::WPRecEvent*) (soff))->~G__TJMcLcLWPRecEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__WPRecEventDict_205_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::WPRecEvent* dest = (JM::WPRecEvent*) G__getstructoffset();
   *dest = *(JM::WPRecEvent*) libp->para[0].ref;
   const JM::WPRecEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JM::WPRecEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncWPRecEventDict {
 public:
  G__Sizep2memfuncWPRecEventDict(): p(&G__Sizep2memfuncWPRecEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncWPRecEventDict::*p)();
};

size_t G__get_sizep2memfuncWPRecEventDict()
{
  G__Sizep2memfuncWPRecEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceWPRecEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent))) {
     JM::WPRecEvent *G__Lderived;
     G__Lderived=(JM::WPRecEvent*)0x1000;
     {
       JM::EventObject *G__Lpbase=(JM::EventObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent),G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLEventObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent),G__get_linked_tagnum(&G__WPRecEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableWPRecEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<JM::RecTrack*>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JM::WPRecEvent */
static void G__setup_memvarJMcLcLWPRecEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent));
   { JM::WPRecEvent *p; p=(JM::WPRecEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR),G__defined_typename("vector<JM::RecTrack*>"),-1,4,"m_wpTracks=",0,"The WP tracks in this event");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__WPRecEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarWPRecEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJMcLcLWPRecEvent(void) {
   /* JM::WPRecEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent));
   G__memfunc_setup("WPRecEvent",963,G__WPRecEventDict_205_0_1, 105, G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTrack",821,G__WPRecEventDict_205_0_2, 85, G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLRecTrack), -1, 0, 1, 1, 1, 9, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addTrack",798,G__WPRecEventDict_205_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JM::RecTrack' - 0 - track", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("wpTracks",847,G__WPRecEventDict_205_0_4, 117, G__get_linked_tagnum(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR), G__defined_typename("vector<JM::RecTrack*>"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__WPRecEventDict_205_0_5, 85, G__get_linked_tagnum(&G__WPRecEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JM::WPRecEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__WPRecEventDict_205_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::WPRecEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__WPRecEventDict_205_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JM::WPRecEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__WPRecEventDict_205_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JM::WPRecEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__WPRecEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__WPRecEventDict_205_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__WPRecEventDict_205_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::WPRecEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__WPRecEventDict_205_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::WPRecEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__WPRecEventDict_205_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::WPRecEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__WPRecEventDict_205_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::WPRecEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("WPRecEvent", 963, G__WPRecEventDict_205_0_17, (int) ('i'), G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent), -1, 0, 1, 1, 1, 0, "u 'JM::WPRecEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~WPRecEvent", 1089, G__WPRecEventDict_205_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__WPRecEventDict_205_0_19, (int) ('u'), G__get_linked_tagnum(&G__WPRecEventDictLN_JMcLcLWPRecEvent), -1, 1, 1, 1, 1, 0, "u 'JM::WPRecEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncWPRecEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalWPRecEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcWPRecEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__WPRecEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_JM = { "JM" , 110 , -1 };
G__linked_taginfo G__WPRecEventDictLN_JMcLcLEventObject = { "JM::EventObject" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_JMcLcLRecTrack = { "JM::RecTrack" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_JMcLcLWPRecEvent = { "JM::WPRecEvent" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR = { "vector<JM::RecTrack*,allocator<JM::RecTrack*> >" , 99 , -1 };
G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<JM::RecTrack*,allocator<JM::RecTrack*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableWPRecEventDict() {
  G__WPRecEventDictLN_TClass.tagnum = -1 ;
  G__WPRecEventDictLN_TBuffer.tagnum = -1 ;
  G__WPRecEventDictLN_TMemberInspector.tagnum = -1 ;
  G__WPRecEventDictLN_TObject.tagnum = -1 ;
  G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__WPRecEventDictLN_JM.tagnum = -1 ;
  G__WPRecEventDictLN_JMcLcLEventObject.tagnum = -1 ;
  G__WPRecEventDictLN_JMcLcLRecTrack.tagnum = -1 ;
  G__WPRecEventDictLN_JMcLcLWPRecEvent.tagnum = -1 ;
  G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR.tagnum = -1 ;
  G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableWPRecEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_JM);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_JMcLcLEventObject);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_JMcLcLRecTrack);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_JMcLcLWPRecEvent),sizeof(JM::WPRecEvent),-1,292096,(char*)NULL,G__setup_memvarJMcLcLWPRecEvent,G__setup_memfuncJMcLcLWPRecEvent);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupWPRecEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupWPRecEventDict()");
  G__set_cpp_environmentWPRecEventDict();
  G__cpp_setup_tagtableWPRecEventDict();

  G__cpp_setup_inheritanceWPRecEventDict();

  G__cpp_setup_typetableWPRecEventDict();

  G__cpp_setup_memvarWPRecEventDict();

  G__cpp_setup_memfuncWPRecEventDict();
  G__cpp_setup_globalWPRecEventDict();
  G__cpp_setup_funcWPRecEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncWPRecEventDict();
  return;
}
class G__cpp_setup_initWPRecEventDict {
  public:
    G__cpp_setup_initWPRecEventDict() { G__add_setup_func("WPRecEventDict",(G__incsetup)(&G__cpp_setupWPRecEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initWPRecEventDict() { G__remove_setup_func("WPRecEventDict"); }
};
G__cpp_setup_initWPRecEventDict G__cpp_setup_initializerWPRecEventDict;

