/********************************************************************
* ../src/WPRecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/WPRecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWPRecEventDict();
extern void G__cpp_setup_inheritanceWPRecEventDict();
extern void G__cpp_setup_typetableWPRecEventDict();
extern void G__cpp_setup_memvarWPRecEventDict();
extern void G__cpp_setup_globalWPRecEventDict();
extern void G__cpp_setup_memfuncWPRecEventDict();
extern void G__cpp_setup_funcWPRecEventDict();
extern void G__set_cpp_environmentWPRecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WPRecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WPRecEventDictLN_TClass;
extern G__linked_taginfo G__WPRecEventDictLN_TBuffer;
extern G__linked_taginfo G__WPRecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__WPRecEventDictLN_TObject;
extern G__linked_taginfo G__WPRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WPRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WPRecEventDictLN_JM;
extern G__linked_taginfo G__WPRecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__WPRecEventDictLN_JMcLcLRecTrack;
extern G__linked_taginfo G__WPRecEventDictLN_JMcLcLWPRecEvent;
extern G__linked_taginfo G__WPRecEventDictLN_vectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgR;
extern G__linked_taginfo G__WPRecEventDictLN_reverse_iteratorlEvectorlEJMcLcLRecTrackmUcOallocatorlEJMcLcLRecTrackmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
