/********************************************************************
* ../src/DummyEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/DummyEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDummyEventDict();
extern void G__cpp_setup_inheritanceDummyEventDict();
extern void G__cpp_setup_typetableDummyEventDict();
extern void G__cpp_setup_memvarDummyEventDict();
extern void G__cpp_setup_globalDummyEventDict();
extern void G__cpp_setup_memfuncDummyEventDict();
extern void G__cpp_setup_funcDummyEventDict();
extern void G__set_cpp_environmentDummyEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DummyEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DummyEventDictLN_TClass;
extern G__linked_taginfo G__DummyEventDictLN_TBuffer;
extern G__linked_taginfo G__DummyEventDictLN_TMemberInspector;
extern G__linked_taginfo G__DummyEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DummyEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyEventDictLN_TClonesArray;
extern G__linked_taginfo G__DummyEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DummyEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyEventDictLN_DummyPMTHit;
extern G__linked_taginfo G__DummyEventDictLN_DummyTTHit;
extern G__linked_taginfo G__DummyEventDictLN_DummyTrack;
extern G__linked_taginfo G__DummyEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DummyEventDictLN_DummyEvent;
extern G__linked_taginfo G__DummyEventDictLN_vectorlEDummyTrackmUcOallocatorlEDummyTrackmUgRsPgR;
extern G__linked_taginfo G__DummyEventDictLN_reverse_iteratorlEvectorlEDummyTrackmUcOallocatorlEDummyTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyEventDictLN_vectorlEDummyPMTHitmUcOallocatorlEDummyPMTHitmUgRsPgR;
extern G__linked_taginfo G__DummyEventDictLN_reverse_iteratorlEvectorlEDummyPMTHitmUcOallocatorlEDummyPMTHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyEventDictLN_vectorlEDummyTTHitmUcOallocatorlEDummyTTHitmUgRsPgR;
extern G__linked_taginfo G__DummyEventDictLN_reverse_iteratorlEvectorlEDummyTTHitmUcOallocatorlEDummyTTHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
