/********************************************************************
* ../src/DummyPMTHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/DummyPMTHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDummyPMTHitDict();
extern void G__cpp_setup_inheritanceDummyPMTHitDict();
extern void G__cpp_setup_typetableDummyPMTHitDict();
extern void G__cpp_setup_memvarDummyPMTHitDict();
extern void G__cpp_setup_globalDummyPMTHitDict();
extern void G__cpp_setup_memfuncDummyPMTHitDict();
extern void G__cpp_setup_funcDummyPMTHitDict();
extern void G__set_cpp_environmentDummyPMTHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DummyPMTHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DummyPMTHitDictLN_TClass;
extern G__linked_taginfo G__DummyPMTHitDictLN_TBuffer;
extern G__linked_taginfo G__DummyPMTHitDictLN_TMemberInspector;
extern G__linked_taginfo G__DummyPMTHitDictLN_TObject;
extern G__linked_taginfo G__DummyPMTHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DummyPMTHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyPMTHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DummyPMTHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyPMTHitDictLN_DummyPMTHit;
extern G__linked_taginfo G__DummyPMTHitDictLN_vectorlEDummyPMTHitcOallocatorlEDummyPMTHitgRsPgR;
extern G__linked_taginfo G__DummyPMTHitDictLN_vectorlEDummyPMTHitcOallocatorlEDummyPMTHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__DummyPMTHitDictLN_reverse_iteratorlEvectorlEDummyPMTHitcOallocatorlEDummyPMTHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<DummyPMTHit,allocator<DummyPMTHit> > G__vectorlEDummyPMTHitcOallocatorlEDummyPMTHitgRsPgR;
