/********************************************************************
* ../src/DummyHeaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/DummyHeaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDummyHeaderDict();
extern void G__cpp_setup_inheritanceDummyHeaderDict();
extern void G__cpp_setup_typetableDummyHeaderDict();
extern void G__cpp_setup_memvarDummyHeaderDict();
extern void G__cpp_setup_globalDummyHeaderDict();
extern void G__cpp_setup_memfuncDummyHeaderDict();
extern void G__cpp_setup_funcDummyHeaderDict();
extern void G__set_cpp_environmentDummyHeaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DummyHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DummyHeaderDictLN_TClass;
extern G__linked_taginfo G__DummyHeaderDictLN_TBuffer;
extern G__linked_taginfo G__DummyHeaderDictLN_TMemberInspector;
extern G__linked_taginfo G__DummyHeaderDictLN_string;
extern G__linked_taginfo G__DummyHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DummyHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DummyHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DummyHeaderDictLN_DummyHeader;

/* STUB derived class for protected member access */
