/********************************************************************
* ../src/SmartRefDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SmartRefDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSmartRefDict();
extern void G__cpp_setup_inheritanceSmartRefDict();
extern void G__cpp_setup_typetableSmartRefDict();
extern void G__cpp_setup_memvarSmartRefDict();
extern void G__cpp_setup_globalSmartRefDict();
extern void G__cpp_setup_memfuncSmartRefDict();
extern void G__cpp_setup_funcSmartRefDict();
extern void G__set_cpp_environmentSmartRefDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SmartRef.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SmartRefDictLN_TClass;
extern G__linked_taginfo G__SmartRefDictLN_TBuffer;
extern G__linked_taginfo G__SmartRefDictLN_TMemberInspector;
extern G__linked_taginfo G__SmartRefDictLN_TObject;
extern G__linked_taginfo G__SmartRefDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SmartRefDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SmartRefDictLN_TProcessID;
extern G__linked_taginfo G__SmartRefDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SmartRefDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SmartRefDictLN_JM;
extern G__linked_taginfo G__SmartRefDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__SmartRefDictLN_JMcLcLSmartRef;

/* STUB derived class for protected member access */
