CMTPATH=/junofs/production/public/users/zhangfy/offline_bgd:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMT_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26/${CMTBIN}:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-c/6.1.9/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/libmore/0.8.3/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Geant4/9.4.p04/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/HepMC/2.06.09/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/CLHEP/2.1.0.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/fftw3/3.2.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/gsl/1.16/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Xercesc/3.1.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Cmake/2.8.12.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/bin:/afs/ihep.ac.cn/soft/common/Python64/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/junofs/production/public/users/zhangfy/local/matlab/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/java/latest/bin:/opt/puppetlabs/bin
CLASSPATH=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags= -O2 -DNDEBUG 
cppflags=-O2 -fPIC -pipe -ansi -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl69-gcc447
GeneratorRelease_tag=$(tag)
GENERATORRELEASEROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/GeneratorRelease
GeneratorRelease_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/GeneratorRelease
GENERATORRELEASEVERSION=v0
GeneratorRelease_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GeneratorRelease_offset=Generator
GeneratorRelease_project=offline
GeneratorRelease_project_release=offline_bgd
InverseBeta_tag=$(tag)
INVERSEBETAROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/InverseBeta
InverseBeta_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/InverseBeta
INVERSEBETAVERSION=v0
InverseBeta_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
InverseBeta_offset=Generator
InverseBeta_project=offline
InverseBeta_project_release=offline_bgd
ROOT_tag=$(tag)
ROOTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/ROOT
ROOT_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
ROOT_offset=Externals
ROOT_project=ExternalInterface
ROOT_home=${JUNO_EXTLIB_ROOT_HOME}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --evelibs` -lMathMore  -lPyROOT 
rootcint="$(ROOT_home)/bin/rootcint"
CLHEP_tag=$(tag)
CLHEPROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/CLHEP
CLHEP_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/CLHEP
CLHEPVERSION=v0
CLHEP_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
CLHEP_offset=Externals
CLHEP_project=ExternalInterface
CLHEP_linkopts= `clhep-config --libs` 
CLHEP_cppflags= `clhep-config --include` 
Muon_tag=$(tag)
MUONROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/Muon
Muon_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/Muon
MUONVERSION=v0
Muon_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Muon_offset=Generator
Muon_project=offline
Muon_project_release=offline_bgd
K40_tag=$(tag)
K40ROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/K40
K40_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/K40
K40VERSION=v0
K40_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
K40_offset=Generator/RadioActivity
K40_project=offline
K40_project_release=offline_bgd
Co60_tag=$(tag)
CO60ROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Co60
Co60_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Co60
CO60VERSION=v0
Co60_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Co60_offset=Generator/RadioActivity
Co60_project=offline
Co60_project_release=offline_bgd
Ge68_tag=$(tag)
GE68ROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Ge68
Ge68_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Ge68
GE68VERSION=v0
Ge68_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Ge68_offset=Generator/RadioActivity
Ge68_project=offline
Ge68_project_release=offline_bgd
Cf252_tag=$(tag)
CF252ROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Cf252
Cf252_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Cf252
CF252VERSION=v0
Cf252_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Cf252_offset=Generator/RadioActivity
Cf252_project=offline
Cf252_project_release=offline_bgd
AmC_tag=$(tag)
AMCROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/AmC
AmC_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/AmC
AMCVERSION=v0
AmC_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
AmC_offset=Generator/RadioActivity
AmC_project=offline
AmC_project_release=offline_bgd
AmBe_tag=$(tag)
AMBEROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/AmBe
AmBe_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/AmBe
AMBEVERSION=v0
AmBe_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
AmBe_offset=Generator/RadioActivity
AmBe_project=offline
AmBe_project_release=offline_bgd
Cs137_tag=$(tag)
CS137ROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Cs137
Cs137_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/Cs137
CS137VERSION=v0
Cs137_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Cs137_offset=Generator/RadioActivity
Cs137_project=offline
Cs137_project_release=offline_bgd
PuC_tag=$(tag)
PUCROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/PuC
PuC_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/RadioActivity/PuC
PUCVERSION=v0
PuC_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
PuC_offset=Generator/RadioActivity
PuC_project=offline
PuC_project_release=offline_bgd
Supernova_tag=$(tag)
SUPERNOVAROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/Supernova
Supernova_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/Supernova
SUPERNOVAVERSION=v0
Supernova_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Supernova_offset=Generator
Supernova_project=offline
Supernova_project_release=offline_bgd
NuSolGen_tag=$(tag)
NUSOLGENROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/NuSolGen
NuSolGen_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/NuSolGen
NUSOLGENVERSION=v0
NuSolGen_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
NuSolGen_offset=Generator
NuSolGen_project=offline
NuSolGen_project_release=offline_bgd
Geant4_tag=$(tag)
GEANT4ROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Geant4
Geant4_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Geant4
GEANT4VERSION=v0
Geant4_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Geant4_offset=Externals
Geant4_project=ExternalInterface
Geant4_home=${JUNO_EXTLIB_Geant4_HOME}
Geant4_cppflags= `geant4-config --cflags` 
Geant4_linkopts= `geant4-config --libs` 
HepMC_tag=$(tag)
HEPMCROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/HepMC
HepMC_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/HepMC
HEPMCVERSION=v0
HepMC_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
HepMC_offset=Externals
HepMC_project=ExternalInterface
HepMC_home=${JUNO_EXTLIB_HepMC_HOME}
HepMC_linkopts= -L $(HepMC_home)/lib -lHepMC 
HepMC_cppflags= -I$(HepMC_home)/include 
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperKernel
SniperKernel_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperPolicy
SniperPolicy_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Boost
Boost_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Python
Python_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python  -lboost_regex 
includes= $(ppcmd)"$(srcdir)" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/include" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/python:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/python:/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/lib/./python2.7/lib-dynload:/junofs/users/zhukangfu/workdesktop/offline/InstallArea/python:/junofs/users/zhukangfu/workdesktop/offline/InstallArea/amd64_linux26/lib:/usr/lib64/python
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
GenTools_tag=$(tag)
GENTOOLSROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/GenTools
GenTools_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/GenTools
GENTOOLSVERSION=v0
GenTools_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GenTools_offset=Simulation
GenTools_project=offline
GenTools_project_release=offline_bgd
RootWriter_tag=$(tag)
ROOTWRITERROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperSvc/RootWriter
RootWriter_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperSvc/RootWriter
ROOTWRITERVERSION=v0
RootWriter_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
RootWriter_offset=SniperSvc
RootWriter_project=sniper
RootWriter_linkopts= -lRootWriter 
RootWriter_stamps=${ROOTWRITERROOT}/${BINDIR}/RootWriter.stamp 
RootWriter_linker_library=RootWriter
RandomSvc_tag=$(tag)
RANDOMSVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/CommonSvc/RandomSvc
RandomSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/CommonSvc/RandomSvc
RANDOMSVCVERSION=v0
RandomSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
RandomSvc_offset=CommonSvc
RandomSvc_project=offline
RandomSvc_project_release=offline_bgd
RandomSvc_linkopts= -lRandomSvc 
RandomSvc_stamps=${RANDOMSVCROOT}/${BINDIR}/RandomSvc.stamp 
RandomSvc_linker_library=RandomSvc
MCGlobalTimeSvc_tag=$(tag)
MCGLOBALTIMESVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/MCGlobalTimeSvc
MCGlobalTimeSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/MCGlobalTimeSvc
MCGLOBALTIMESVCVERSION=v0
MCGlobalTimeSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
MCGlobalTimeSvc_offset=Simulation/DetSimV2
MCGlobalTimeSvc_project=offline
MCGlobalTimeSvc_project_release=offline_bgd
MCGlobalTimeSvc_linkopts= -lMCGlobalTimeSvc 
MCGlobalTimeSvc_stamps=${MCGLOBALTIMESVCROOT}/${BINDIR}/MCGlobalTimeSvc.stamp 
MCGlobalTimeSvc_linker_library=MCGlobalTimeSvc
EvtNavigator_tag=$(tag)
EVTNAVIGATORROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator
EvtNavigator_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator
EVTNAVIGATORVERSION=v0
EvtNavigator_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
EvtNavigator_offset=DataModel
EvtNavigator_project=offline
EvtNavigator_project_release=offline_bgd
BaseEvent_tag=$(tag)
BASEEVENTROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent
BaseEvent_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent
BASEEVENTVERSION=v0
BaseEvent_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
BaseEvent_offset=DataModel
BaseEvent_project=offline
BaseEvent_project_release=offline_bgd
XmlObjDesc_tag=$(tag)
XMLOBJDESCROOT=/junofs/production/public/users/zhangfy/offline_bgd/XmlObjDesc
XmlObjDesc_root=/junofs/production/public/users/zhangfy/offline_bgd/XmlObjDesc
XMLOBJDESCVERSION=v0
XmlObjDesc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
XmlObjDesc_project=offline
XmlObjDesc_project_release=offline_bgd
xmlsrc=xml
XODflags= -n JM 
BaseEvent_dependencies= BaseEventObj2Doth  BaseEventDict  BaseEventxodsrc 
install_more_includes_dependencies= BaseEventObj2Doth 
BaseEventDict_dependencies= BaseEventObj2Doth  install_more_includes 
BaseEventxodsrc_dependencies= BaseEventObj2Doth 
BaseEvent_linkopts= -lBaseEvent 
BaseEvent_stamps=${BASEEVENTROOT}/${BINDIR}/BaseEvent.stamp 
BaseEvent_linker_library=BaseEvent
EDMUtil_tag=$(tag)
EDMUTILROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil
EDMUtil_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil
EDMUTILVERSION=v0
EDMUtil_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
EDMUtil_offset=DataModel
EDMUtil_project=offline
EDMUtil_project_release=offline_bgd
EDMUtil_dependencies= EDMUtilDict  EDMUtilDict  EDMUtilDict  EDMUtilDict 
EDMUtilDict_dependencies= EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes 
EDMUtil_linkopts= -lEDMUtil 
EDMUtil_stamps=${EDMUTILROOT}/${BINDIR}/EDMUtil.stamp 
EDMUtil_linker_library=EDMUtil
EvtNavigator_cintflags=-I$(CMTINSTALLAREA)/include
EvtNavigator_dependencies= EvtNavigatorDict 
EvtNavigatorDict_dependencies= EvtNavigatorObj2Doth  install_more_includes 
EvtNavigator_linkopts= -lEvtNavigator 
EvtNavigator_stamps=${EVTNAVIGATORROOT}/${BINDIR}/EvtNavigator.stamp 
EvtNavigator_linker_library=EvtNavigator
GenEventV2_tag=$(tag)
GENEVENTV2ROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2
GenEventV2_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2
GENEVENTV2VERSION=v0
GenEventV2_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GenEventV2_offset=DataModel
GenEventV2_project=offline
GenEventV2_project_release=offline_bgd
GenHeader_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT)  $(HepMC_cppflags) 
GenEvent_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  $(HepMC_cppflags) 
GenEventV2_dependencies= GenEventV2Dict 
GenEventV2Dict_dependencies= GenEventV2Obj2Doth  install_more_includes 
GenEventV2_linkopts= -lGenEventV2 
GenEventV2_stamps=${GENEVENTV2ROOT}/${BINDIR}/GenEventV2.stamp 
GenEventV2_linker_library=GenEventV2
GenTools_use_linkopts= -lEG 
GenTools_linkopts= -lGenTools 
GenTools_stamps=${GENTOOLSROOT}/${BINDIR}/GenTools.stamp 
GenTools_linker_library=GenTools
NuSolGen_linkopts= -lNuSolGen 
NuSolGen_stamps=${NUSOLGENROOT}/${BINDIR}/NuSolGen.stamp 
NuSolGen_linker_library=NuSolGen
DSNB_tag=$(tag)
DSNBROOT=/junofs/production/public/users/zhangfy/offline_bgd/Generator/DSNB
DSNB_root=/junofs/production/public/users/zhangfy/offline_bgd/Generator/DSNB
DSNBVERSION=v0
DSNB_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
DSNB_offset=Generator
DSNB_project=offline
DSNB_project_release=offline_bgd
tag=amd64_linux26
package=GeneratorRelease
version=v0
PACKAGE_ROOT=$(GENERATORRELEASEROOT)
srcdir=../src
bin=../$(GeneratorRelease_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/junofs/production/public/users/zhangfy/offline_bgd/Generator/GeneratorRelease/amd64_linux26/
project=offline
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(GeneratorRelease_linkopts)  $(InverseBeta_linkopts)  $(Muon_linkopts)  $(K40_linkopts)  $(Co60_linkopts)  $(Ge68_linkopts)  $(Cf252_linkopts)  $(AmC_linkopts)  $(AmBe_linkopts)  $(Cs137_linkopts)  $(PuC_linkopts)  $(Supernova_linkopts)  $(NuSolGen_linkopts)  $(GenTools_linkopts)  $(RootWriter_linkopts)  $(RandomSvc_linkopts)  $(MCGlobalTimeSvc_linkopts)  $(EvtNavigator_linkopts)  $(GenEventV2_linkopts)  $(EDMUtil_linkopts)  $(BaseEvent_linkopts)  $(DSNB_linkopts)  $(ROOT_linkopts)  $(CLHEP_linkopts)  $(Geant4_linkopts)  $(HepMC_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-c/6.1.9/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/libmore/0.8.3/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/lib/geant4-9.4.4/Linux-g++:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CLHEP/2.1.0.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Geant4/9.4.p04/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/HepMC/2.06.09/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/CLHEP/2.1.0.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/fftw3/3.2.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/gsl/1.16/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Xercesc/3.1.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/lib:/junofs/production/public/users/zhangfy/local/matlab/bin/glnxa64:/junofs/production/public/users/zhangfy/local/matlab/sys/os/glnxa64:/usr/lib64/classads:/usr/lib64:/usr/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
cmt_installarea_linkopts= -L/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
sniper_home=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
offline_home=/junofs/production/public/users/zhangfy/offline_bgd
offline_install_include= /junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/include 
sniper_install_include= /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/$(tag)/lib
offline_python_path=/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/$(tag)/lib
sniper_install_python=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/python
offline_install_python=/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/python
CMTINSTALLAREA=/junofs/production/public/users/zhangfy/offline_bgd/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(InverseBeta_root)/cmt/requirements $(Muon_root)/cmt/requirements $(K40_root)/cmt/requirements $(Co60_root)/cmt/requirements $(Ge68_root)/cmt/requirements $(Cf252_root)/cmt/requirements $(AmC_root)/cmt/requirements $(AmBe_root)/cmt/requirements $(Cs137_root)/cmt/requirements $(PuC_root)/cmt/requirements $(Supernova_root)/cmt/requirements $(NuSolGen_root)/cmt/requirements $(GenTools_root)/cmt/requirements $(RootWriter_root)/cmt/requirements $(RandomSvc_root)/cmt/requirements $(MCGlobalTimeSvc_root)/cmt/requirements $(EvtNavigator_root)/cmt/requirements $(GenEventV2_root)/cmt/requirements $(EDMUtil_root)/cmt/requirements $(BaseEvent_root)/cmt/requirements $(XmlObjDesc_root)/cmt/requirements $(DSNB_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(Geant4_root)/cmt/requirements $(HepMC_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements 
use_includes= $(ppcmd)"$(InverseBeta_root)/src" $(ppcmd)"$(Muon_root)/src" $(ppcmd)"$(K40_root)/src" $(ppcmd)"$(Co60_root)/src" $(ppcmd)"$(Ge68_root)/src" $(ppcmd)"$(Cf252_root)/src" $(ppcmd)"$(AmC_root)/src" $(ppcmd)"$(AmBe_root)/src" $(ppcmd)"$(Cs137_root)/src" $(ppcmd)"$(PuC_root)/src" $(ppcmd)"$(Supernova_root)/src" $(ppcmd)"$(NuSolGen_root)/src" $(ppcmd)"$(GenTools_root)/src" $(ppcmd)"$(RootWriter_root)/src" $(ppcmd)"$(RandomSvc_root)/src" $(ppcmd)"$(MCGlobalTimeSvc_root)/src" $(ppcmd)"$(EvtNavigator_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator/EvtNavigator" $(ppcmd)"$(GenEventV2_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2/" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2/Event" $(ppcmd)"$(EDMUtil_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil/include" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil/EDMUtil" $(ppcmd)"$(BaseEvent_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent/Event" $(ppcmd)"$(DSNB_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/include" $(ppcmd)"$(CLHEP_root)/src" $(ppcmd)"$(Geant4_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/include/geant4" $(ppcmd)"$(HepMC_root)/src" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/include" $(ppcmd)"$(Python_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(GeneratorRelease_stamps)  $(InverseBeta_stamps)  $(Muon_stamps)  $(K40_stamps)  $(Co60_stamps)  $(Ge68_stamps)  $(Cf252_stamps)  $(AmC_stamps)  $(AmBe_stamps)  $(Cs137_stamps)  $(PuC_stamps)  $(Supernova_stamps)  $(NuSolGen_stamps)  $(GenTools_stamps)  $(RootWriter_stamps)  $(RandomSvc_stamps)  $(MCGlobalTimeSvc_stamps)  $(EvtNavigator_stamps)  $(GenEventV2_stamps)  $(EDMUtil_stamps)  $(BaseEvent_stamps)  $(DSNB_stamps)  $(ROOT_stamps)  $(CLHEP_stamps)  $(Geant4_stamps)  $(HepMC_stamps)  $(SniperKernel_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps) 
use_cflags=  $(GeneratorRelease_cflags)  $(InverseBeta_cflags)  $(Muon_cflags)  $(K40_cflags)  $(Co60_cflags)  $(Ge68_cflags)  $(Cf252_cflags)  $(AmC_cflags)  $(AmBe_cflags)  $(Cs137_cflags)  $(PuC_cflags)  $(Supernova_cflags)  $(NuSolGen_cflags)  $(GenTools_cflags)  $(RootWriter_cflags)  $(RandomSvc_cflags)  $(MCGlobalTimeSvc_cflags)  $(EvtNavigator_cflags)  $(GenEventV2_cflags)  $(EDMUtil_cflags)  $(BaseEvent_cflags)  $(DSNB_cflags)  $(ROOT_cflags)  $(CLHEP_cflags)  $(Geant4_cflags)  $(HepMC_cflags)  $(SniperKernel_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags) 
use_pp_cflags=  $(GeneratorRelease_pp_cflags)  $(InverseBeta_pp_cflags)  $(Muon_pp_cflags)  $(K40_pp_cflags)  $(Co60_pp_cflags)  $(Ge68_pp_cflags)  $(Cf252_pp_cflags)  $(AmC_pp_cflags)  $(AmBe_pp_cflags)  $(Cs137_pp_cflags)  $(PuC_pp_cflags)  $(Supernova_pp_cflags)  $(NuSolGen_pp_cflags)  $(GenTools_pp_cflags)  $(RootWriter_pp_cflags)  $(RandomSvc_pp_cflags)  $(MCGlobalTimeSvc_pp_cflags)  $(EvtNavigator_pp_cflags)  $(GenEventV2_pp_cflags)  $(EDMUtil_pp_cflags)  $(BaseEvent_pp_cflags)  $(DSNB_pp_cflags)  $(ROOT_pp_cflags)  $(CLHEP_pp_cflags)  $(Geant4_pp_cflags)  $(HepMC_pp_cflags)  $(SniperKernel_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags) 
use_cppflags=  $(GeneratorRelease_cppflags)  $(InverseBeta_cppflags)  $(Muon_cppflags)  $(K40_cppflags)  $(Co60_cppflags)  $(Ge68_cppflags)  $(Cf252_cppflags)  $(AmC_cppflags)  $(AmBe_cppflags)  $(Cs137_cppflags)  $(PuC_cppflags)  $(Supernova_cppflags)  $(NuSolGen_cppflags)  $(GenTools_cppflags)  $(RootWriter_cppflags)  $(RandomSvc_cppflags)  $(MCGlobalTimeSvc_cppflags)  $(EvtNavigator_cppflags)  $(GenEventV2_cppflags)  $(EDMUtil_cppflags)  $(BaseEvent_cppflags)  $(DSNB_cppflags)  $(ROOT_cppflags)  $(CLHEP_cppflags)  $(Geant4_cppflags)  $(HepMC_cppflags)  $(SniperKernel_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags) 
use_pp_cppflags=  $(GeneratorRelease_pp_cppflags)  $(InverseBeta_pp_cppflags)  $(Muon_pp_cppflags)  $(K40_pp_cppflags)  $(Co60_pp_cppflags)  $(Ge68_pp_cppflags)  $(Cf252_pp_cppflags)  $(AmC_pp_cppflags)  $(AmBe_pp_cppflags)  $(Cs137_pp_cppflags)  $(PuC_pp_cppflags)  $(Supernova_pp_cppflags)  $(NuSolGen_pp_cppflags)  $(GenTools_pp_cppflags)  $(RootWriter_pp_cppflags)  $(RandomSvc_pp_cppflags)  $(MCGlobalTimeSvc_pp_cppflags)  $(EvtNavigator_pp_cppflags)  $(GenEventV2_pp_cppflags)  $(EDMUtil_pp_cppflags)  $(BaseEvent_pp_cppflags)  $(DSNB_pp_cppflags)  $(ROOT_pp_cppflags)  $(CLHEP_pp_cppflags)  $(Geant4_pp_cppflags)  $(HepMC_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags) 
use_fflags=  $(GeneratorRelease_fflags)  $(InverseBeta_fflags)  $(Muon_fflags)  $(K40_fflags)  $(Co60_fflags)  $(Ge68_fflags)  $(Cf252_fflags)  $(AmC_fflags)  $(AmBe_fflags)  $(Cs137_fflags)  $(PuC_fflags)  $(Supernova_fflags)  $(NuSolGen_fflags)  $(GenTools_fflags)  $(RootWriter_fflags)  $(RandomSvc_fflags)  $(MCGlobalTimeSvc_fflags)  $(EvtNavigator_fflags)  $(GenEventV2_fflags)  $(EDMUtil_fflags)  $(BaseEvent_fflags)  $(DSNB_fflags)  $(ROOT_fflags)  $(CLHEP_fflags)  $(Geant4_fflags)  $(HepMC_fflags)  $(SniperKernel_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags) 
use_pp_fflags=  $(GeneratorRelease_pp_fflags)  $(InverseBeta_pp_fflags)  $(Muon_pp_fflags)  $(K40_pp_fflags)  $(Co60_pp_fflags)  $(Ge68_pp_fflags)  $(Cf252_pp_fflags)  $(AmC_pp_fflags)  $(AmBe_pp_fflags)  $(Cs137_pp_fflags)  $(PuC_pp_fflags)  $(Supernova_pp_fflags)  $(NuSolGen_pp_fflags)  $(GenTools_pp_fflags)  $(RootWriter_pp_fflags)  $(RandomSvc_pp_fflags)  $(MCGlobalTimeSvc_pp_fflags)  $(EvtNavigator_pp_fflags)  $(GenEventV2_pp_fflags)  $(EDMUtil_pp_fflags)  $(BaseEvent_pp_fflags)  $(DSNB_pp_fflags)  $(ROOT_pp_fflags)  $(CLHEP_pp_fflags)  $(Geant4_pp_fflags)  $(HepMC_pp_fflags)  $(SniperKernel_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags) 
use_libraries= $(InverseBeta_libraries)  $(Muon_libraries)  $(K40_libraries)  $(Co60_libraries)  $(Ge68_libraries)  $(Cf252_libraries)  $(AmC_libraries)  $(AmBe_libraries)  $(Cs137_libraries)  $(PuC_libraries)  $(Supernova_libraries)  $(NuSolGen_libraries)  $(GenTools_libraries)  $(RootWriter_libraries)  $(RandomSvc_libraries)  $(MCGlobalTimeSvc_libraries)  $(EvtNavigator_libraries)  $(GenEventV2_libraries)  $(EDMUtil_libraries)  $(BaseEvent_libraries)  $(XmlObjDesc_libraries)  $(DSNB_libraries)  $(ROOT_libraries)  $(CLHEP_libraries)  $(Geant4_libraries)  $(HepMC_libraries)  $(SniperKernel_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries) 
fincludes= $(includes)
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= 
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
