/********************************************************************
* ../src/EventObjectDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/EventObjectDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventObjectDict();
extern void G__cpp_setup_inheritanceEventObjectDict();
extern void G__cpp_setup_typetableEventObjectDict();
extern void G__cpp_setup_memvarEventObjectDict();
extern void G__cpp_setup_globalEventObjectDict();
extern void G__cpp_setup_memfuncEventObjectDict();
extern void G__cpp_setup_funcEventObjectDict();
extern void G__set_cpp_environmentEventObjectDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventObject.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventObjectDictLN_TClass;
extern G__linked_taginfo G__EventObjectDictLN_TBuffer;
extern G__linked_taginfo G__EventObjectDictLN_TMemberInspector;
extern G__linked_taginfo G__EventObjectDictLN_TObject;
extern G__linked_taginfo G__EventObjectDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventObjectDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventObjectDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventObjectDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventObjectDictLN_JM;
extern G__linked_taginfo G__EventObjectDictLN_JMcLcLEventObject;

/* STUB derived class for protected member access */
