/********************************************************************
* ../src/GenEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/GenEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGenEventDict();
extern void G__cpp_setup_inheritanceGenEventDict();
extern void G__cpp_setup_typetableGenEventDict();
extern void G__cpp_setup_memvarGenEventDict();
extern void G__cpp_setup_globalGenEventDict();
extern void G__cpp_setup_memfuncGenEventDict();
extern void G__cpp_setup_funcGenEventDict();
extern void G__set_cpp_environmentGenEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GenEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GenEventDictLN_TClass;
extern G__linked_taginfo G__GenEventDictLN_TBuffer;
extern G__linked_taginfo G__GenEventDictLN_TMemberInspector;
extern G__linked_taginfo G__GenEventDictLN_TObject;
extern G__linked_taginfo G__GenEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GenEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenEventDictLN_JM;
extern G__linked_taginfo G__GenEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__GenEventDictLN_HepMC;
extern G__linked_taginfo G__GenEventDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_HepMCcLcLGenEvent;
extern G__linked_taginfo G__GenEventDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenEventDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR;
extern G__linked_taginfo G__GenEventDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR;
extern G__linked_taginfo G__GenEventDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR;
extern G__linked_taginfo G__GenEventDictLN_JMcLcLGenEvent;

/* STUB derived class for protected member access */
