//
// File generated by /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin/rootcint at Thu Dec 28 13:51:19 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIsrcdIGenHeaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GenHeaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JMcLcLGenHeader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JMcLcLGenHeader(void *p = 0);
   static void *newArray_JMcLcLGenHeader(Long_t size, void *p);
   static void delete_JMcLcLGenHeader(void *p);
   static void deleteArray_JMcLcLGenHeader(void *p);
   static void destruct_JMcLcLGenHeader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JM::GenHeader*)
   {
      ::JM::GenHeader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JM::GenHeader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JM::GenHeader", ::JM::GenHeader::Class_Version(), "./GenHeader.h", 13,
                  typeid(::JM::GenHeader), DefineBehavior(ptr, ptr),
                  &::JM::GenHeader::Dictionary, isa_proxy, 4,
                  sizeof(::JM::GenHeader) );
      instance.SetNew(&new_JMcLcLGenHeader);
      instance.SetNewArray(&newArray_JMcLcLGenHeader);
      instance.SetDelete(&delete_JMcLcLGenHeader);
      instance.SetDeleteArray(&deleteArray_JMcLcLGenHeader);
      instance.SetDestructor(&destruct_JMcLcLGenHeader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JM::GenHeader*)
   {
      return GenerateInitInstanceLocal((::JM::GenHeader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JM::GenHeader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace JM {
//______________________________________________________________________________
TClass *GenHeader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GenHeader::Class_Name()
{
   return "JM::GenHeader";
}

//______________________________________________________________________________
const char *GenHeader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::GenHeader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GenHeader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::GenHeader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GenHeader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::GenHeader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GenHeader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::GenHeader*)0x0)->GetClass();
   return fgIsA;
}

} // namespace JM
      namespace JM {
//______________________________________________________________________________
void GenHeader::Streamer(TBuffer &R__b)
{
   // Stream an object of class JM::GenHeader.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JM::GenHeader::Class(),this);
   } else {
      R__b.WriteClassBuffer(JM::GenHeader::Class(),this);
   }
}

} // namespace JM
//______________________________________________________________________________
      namespace JM {
void GenHeader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JM::GenHeader.
      TClass *R__cl = ::JM::GenHeader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_event", &m_event);
      R__insp.InspectMember(m_event, "m_event.");
      //This works around a msvc bug and should be harmless on other platforms
      typedef JM::HeaderObject baseClass1;
      baseClass1::ShowMembers(R__insp);
}

} // namespace JM
namespace ROOT {
   // Wrappers around operator new
   static void *new_JMcLcLGenHeader(void *p) {
      return  p ? new(p) ::JM::GenHeader : new ::JM::GenHeader;
   }
   static void *newArray_JMcLcLGenHeader(Long_t nElements, void *p) {
      return p ? new(p) ::JM::GenHeader[nElements] : new ::JM::GenHeader[nElements];
   }
   // Wrapper around operator delete
   static void delete_JMcLcLGenHeader(void *p) {
      delete ((::JM::GenHeader*)p);
   }
   static void deleteArray_JMcLcLGenHeader(void *p) {
      delete [] ((::JM::GenHeader*)p);
   }
   static void destruct_JMcLcLGenHeader(void *p) {
      typedef ::JM::GenHeader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JM::GenHeader

/********************************************************
* ../src/GenHeaderDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGenHeaderDict();

extern "C" void G__set_cpp_environmentGenHeaderDict() {
  G__cpp_reset_tagtableGenHeaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevGenHeaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JM::GenHeader */
static int G__GenHeaderDict_545_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::GenHeader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::GenHeader[n];
     } else {
       p = new((void*) gvp) JM::GenHeader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::GenHeader;
     } else {
       p = new((void*) gvp) JM::GenHeader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::GenHeader*) G__getstructoffset())->event());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::GenHeader*) G__getstructoffset())->setEvent((JM::GenEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JM::GenHeader*) G__getstructoffset())->hasEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JM::GenHeader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::GenHeader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JM::GenHeader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JM::GenHeader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::GenHeader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::GenHeader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::GenHeader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::GenHeader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenHeaderDict_545_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::GenHeader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GenHeaderDict_545_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JM::GenHeader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JM::GenHeader(*(JM::GenHeader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JM::GenHeader G__TJMcLcLGenHeader;
static int G__GenHeaderDict_545_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JM::GenHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JM::GenHeader*) (soff+(sizeof(JM::GenHeader)*i)))->~G__TJMcLcLGenHeader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JM::GenHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JM::GenHeader*) (soff))->~G__TJMcLcLGenHeader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GenHeaderDict_545_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::GenHeader* dest = (JM::GenHeader*) G__getstructoffset();
   *dest = *(JM::GenHeader*) libp->para[0].ref;
   const JM::GenHeader& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JM::GenHeader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGenHeaderDict {
 public:
  G__Sizep2memfuncGenHeaderDict(): p(&G__Sizep2memfuncGenHeaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGenHeaderDict::*p)();
};

size_t G__get_sizep2memfuncGenHeaderDict()
{
  G__Sizep2memfuncGenHeaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGenHeaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader))) {
     JM::GenHeader *G__Lderived;
     G__Lderived=(JM::GenHeader*)0x1000;
     {
       JM::HeaderObject *G__Lpbase=(JM::HeaderObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader),G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLHeaderObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       JM::EventObject *G__Lpbase=(JM::EventObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader),G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLEventObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader),G__get_linked_tagnum(&G__GenHeaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGenHeaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,size_type>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,size_type>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned long>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned long,less<string> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::forward_iterator_tag,HepMC::GenParticle*,ptrdiff_t>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,ptrdiff_t>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,long>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,long,HepMC::GenParticle**>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::forward_iterator_tag,HepMC::GenVertex*,ptrdiff_t>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,ptrdiff_t>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,long>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,long,HepMC::GenVertex**>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const HepMC::GenVertex*,less<const HepMC::GenVertex*> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*,std::greater<int> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*,greater<int> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*,less<int> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*,std::less<int> >",117,G__get_linked_tagnum(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JM::GenHeader */
static void G__setup_memvarJMcLcLGenHeader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader));
   { JM::GenHeader *p; p=(JM::GenHeader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLSmartRef),-1,-1,4,"m_event=",0,"||");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GenHeaderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGenHeaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJMcLcLGenHeader(void) {
   /* JM::GenHeader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader));
   G__memfunc_setup("GenHeader",867,G__GenHeaderDict_545_0_1, 105, G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("event",546,G__GenHeaderDict_545_0_2, 85, G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLEventObject), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEvent",846,G__GenHeaderDict_545_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JM::GenEvent' - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEventEntry",1376,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - eventName n - 'Long64_t' 1 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("event",546,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLEventObject), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - eventName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("hasEvent",830,G__GenHeaderDict_545_0_6, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GenHeaderDict_545_0_7, 85, G__get_linked_tagnum(&G__GenHeaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JM::GenHeader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GenHeaderDict_545_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::GenHeader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GenHeaderDict_545_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JM::GenHeader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GenHeaderDict_545_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JM::GenHeader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GenHeaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GenHeaderDict_545_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GenHeaderDict_545_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::GenHeader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GenHeaderDict_545_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::GenHeader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GenHeaderDict_545_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::GenHeader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GenHeaderDict_545_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::GenHeader::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GenHeader", 867, G__GenHeaderDict_545_0_19, (int) ('i'), G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader), -1, 0, 1, 1, 1, 0, "u 'JM::GenHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GenHeader", 993, G__GenHeaderDict_545_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GenHeaderDict_545_0_21, (int) ('u'), G__get_linked_tagnum(&G__GenHeaderDictLN_JMcLcLGenHeader), -1, 1, 1, 1, 1, 0, "u 'JM::GenHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGenHeaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGenHeaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGenHeaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GenHeaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JM = { "JM" , 110 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JMcLcLEventObject = { "JM::EventObject" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JMcLcLHeaderObject = { "JM::HeaderObject" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR = { "map<string,unsigned long,less<string>,allocator<pair<const string,unsigned long> > >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR = { "vector<HepMC::GenParticle*,allocator<HepMC::GenParticle*> >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HepMC::GenParticle*,allocator<HepMC::GenParticle*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR = { "iterator<forward_iterator_tag,HepMC::GenParticle*,long,HepMC::GenParticle**,HepMC::GenParticle*&>" , 115 , -1 };
G__linked_taginfo G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR = { "iterator<forward_iterator_tag,HepMC::GenVertex*,long,HepMC::GenVertex**,HepMC::GenVertex*&>" , 115 , -1 };
G__linked_taginfo G__GenHeaderDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR = { "set<const HepMC::GenVertex*,less<const HepMC::GenVertex*>,allocator<const HepMC::GenVertex*> >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR = { "map<int,HepMC::GenVertex*,greater<int>,allocator<pair<const int,HepMC::GenVertex*> > >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR = { "map<int,HepMC::GenParticle*,less<int>,allocator<pair<const int,HepMC::GenParticle*> > >" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JMcLcLGenEvent = { "JM::GenEvent" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JMcLcLSmartRef = { "JM::SmartRef" , 99 , -1 };
G__linked_taginfo G__GenHeaderDictLN_JMcLcLGenHeader = { "JM::GenHeader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGenHeaderDict() {
  G__GenHeaderDictLN_TClass.tagnum = -1 ;
  G__GenHeaderDictLN_TBuffer.tagnum = -1 ;
  G__GenHeaderDictLN_TMemberInspector.tagnum = -1 ;
  G__GenHeaderDictLN_TObject.tagnum = -1 ;
  G__GenHeaderDictLN_string.tagnum = -1 ;
  G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenHeaderDictLN_JM.tagnum = -1 ;
  G__GenHeaderDictLN_JMcLcLEventObject.tagnum = -1 ;
  G__GenHeaderDictLN_JMcLcLHeaderObject.tagnum = -1 ;
  G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR.tagnum = -1 ;
  G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR.tagnum = -1 ;
  G__GenHeaderDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR.tagnum = -1 ;
  G__GenHeaderDictLN_JMcLcLGenEvent.tagnum = -1 ;
  G__GenHeaderDictLN_JMcLcLSmartRef.tagnum = -1 ;
  G__GenHeaderDictLN_JMcLcLGenHeader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGenHeaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_string);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JM);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JMcLcLEventObject);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JMcLcLHeaderObject);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JMcLcLGenEvent);
   G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JMcLcLSmartRef);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GenHeaderDictLN_JMcLcLGenHeader),sizeof(JM::GenHeader),-1,292096,(char*)NULL,G__setup_memvarJMcLcLGenHeader,G__setup_memfuncJMcLcLGenHeader);
}
extern "C" void G__cpp_setupGenHeaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGenHeaderDict()");
  G__set_cpp_environmentGenHeaderDict();
  G__cpp_setup_tagtableGenHeaderDict();

  G__cpp_setup_inheritanceGenHeaderDict();

  G__cpp_setup_typetableGenHeaderDict();

  G__cpp_setup_memvarGenHeaderDict();

  G__cpp_setup_memfuncGenHeaderDict();
  G__cpp_setup_globalGenHeaderDict();
  G__cpp_setup_funcGenHeaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGenHeaderDict();
  return;
}
class G__cpp_setup_initGenHeaderDict {
  public:
    G__cpp_setup_initGenHeaderDict() { G__add_setup_func("GenHeaderDict",(G__incsetup)(&G__cpp_setupGenHeaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGenHeaderDict() { G__remove_setup_func("GenHeaderDict"); }
};
G__cpp_setup_initGenHeaderDict G__cpp_setup_initializerGenHeaderDict;

