/********************************************************************
* ../src/DBITableRowDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/DBITableRowDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDBITableRowDict();
extern void G__cpp_setup_inheritanceDBITableRowDict();
extern void G__cpp_setup_typetableDBITableRowDict();
extern void G__cpp_setup_memvarDBITableRowDict();
extern void G__cpp_setup_globalDBITableRowDict();
extern void G__cpp_setup_memfuncDBITableRowDict();
extern void G__cpp_setup_funcDBITableRowDict();
extern void G__set_cpp_environmentDBITableRowDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DBITableRow.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DBITableRowDictLN_TClass;
extern G__linked_taginfo G__DBITableRowDictLN_TBuffer;
extern G__linked_taginfo G__DBITableRowDictLN_TMemberInspector;
extern G__linked_taginfo G__DBITableRowDictLN_TObject;
extern G__linked_taginfo G__DBITableRowDictLN_string;
extern G__linked_taginfo G__DBITableRowDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DBITableRowDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DBITableRowDictLN_TList;
extern G__linked_taginfo G__DBITableRowDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DBITableRowDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DBITableRowDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DBITableRowDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DBITableRowDictLN_DBITableRow;

/* STUB derived class for protected member access */
