CMTPATH=/junofs/production/public/users/zhangfy/offline_bgd:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMT_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/${CMTCONFIG}/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26/${CMTBIN}:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-c/6.1.9/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/libmore/0.8.3/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Geant4/9.4.p04/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/HepMC/2.06.09/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/CLHEP/2.1.0.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/fftw3/3.2.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/gsl/1.16/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Xercesc/3.1.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Cmake/2.8.12.1/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/bin:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/bin:/afs/ihep.ac.cn/soft/common/Python64/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/junofs/production/public/users/zhangfy/local/matlab/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/java/latest/bin:/opt/puppetlabs/bin
CLASSPATH=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-O2 -fPIC -pipe -ansi -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl69-gcc447
AnalysisCode_tag=$(tag)
ANALYSISCODEROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/AnalysisCode
AnalysisCode_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/AnalysisCode
ANALYSISCODEVERSION=v0
AnalysisCode_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
AnalysisCode_offset=Simulation/DetSimV2
AnalysisCode_project=offline
AnalysisCode_project_release=offline_bgd
SniperRelease_tag=$(tag)
SNIPERRELEASEROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperRelease
SniperRelease_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperRelease
SNIPERRELEASEVERSION=v2
SniperRelease_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
SniperRelease_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperPolicy
SniperPolicy_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperKernel
SniperKernel_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
SniperKernel_project=sniper
Boost_tag=$(tag)
BOOSTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Boost
Boost_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Python
Python_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python  -lboost_regex  -lboost_filesystem -lboost_system  -lboost_filesystem -lboost_system 
includes= $(ppcmd)"$(srcdir)" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/AnalysisCode/include" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DAE/include" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/include" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/python:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/python:/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/amd64_linux26/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/lib/./python2.7/lib-dynload:/junofs/users/zhukangfu/workdesktop/offline/InstallArea/python:/junofs/users/zhukangfu/workdesktop/offline/InstallArea/amd64_linux26/lib:/usr/lib64/python
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
DataBuffer_tag=$(tag)
DATABUFFERROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperUtil/DataBuffer
DataBuffer_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperUtil/DataBuffer
DATABUFFERVERSION=v0
DataBuffer_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
DataBuffer_offset=SniperUtil
DataBuffer_project=sniper
HelloWorld_tag=$(tag)
HELLOWORLDROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/Examples/HelloWorld
HelloWorld_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/Examples/HelloWorld
HELLOWORLDVERSION=v1
HelloWorld_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
HelloWorld_offset=Examples
HelloWorld_project=sniper
RootWriter_tag=$(tag)
ROOTWRITERROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperSvc/RootWriter
RootWriter_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/SniperSvc/RootWriter
ROOTWRITERVERSION=v0
RootWriter_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
RootWriter_offset=SniperSvc
RootWriter_project=sniper
ROOT_tag=$(tag)
ROOTROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/ROOT
ROOT_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
ROOT_offset=Externals
ROOT_project=ExternalInterface
ROOT_home=${JUNO_EXTLIB_ROOT_HOME}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --evelibs` -lPyROOT  `root-config --evelibs` 
rootcint="$(ROOT_home)/bin/rootcint"
RootWriter_linkopts= -lRootWriter 
RootWriter_stamps=${ROOTWRITERROOT}/${BINDIR}/RootWriter.stamp 
RootWriter_linker_library=RootWriter
DummyAlg_tag=$(tag)
DUMMYALGROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/Examples/DummyAlg
DummyAlg_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/Examples/DummyAlg
DUMMYALGVERSION=v0
DummyAlg_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
DummyAlg_offset=Examples
DummyAlg_project=sniper
DetSimPolicy_tag=$(tag)
DETSIMPOLICYROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DetSimPolicy
DetSimPolicy_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DetSimPolicy
DETSIMPOLICYVERSION=v0
DetSimPolicy_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
DetSimPolicy_offset=Simulation/DetSimV2
DetSimPolicy_project=offline
DetSimPolicy_project_release=offline_bgd
Geant4_tag=$(tag)
GEANT4ROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Geant4
Geant4_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Geant4
GEANT4VERSION=v0
Geant4_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Geant4_offset=Externals
Geant4_project=ExternalInterface
Geant4_home=${JUNO_EXTLIB_Geant4_HOME}
Geant4_cppflags= `geant4-config --cflags` 
Geant4_linkopts= `geant4-config --libs` 
CLHEP_tag=$(tag)
CLHEPROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/CLHEP
CLHEP_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/CLHEP
CLHEPVERSION=v0
CLHEP_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
CLHEP_offset=Externals
CLHEP_project=ExternalInterface
CLHEP_linkopts= `clhep-config --libs` 
CLHEP_cppflags= `clhep-config --include` 
Xercesc_tag=$(tag)
XERCESCROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Xercesc
Xercesc_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/Xercesc
XERCESCVERSION=v0
Xercesc_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
Xercesc_offset=Externals
Xercesc_project=ExternalInterface
Xercesc_linkopts= `pkg-config --libs xerces-c` 
Xercesc_cppflags= `pkg-config --cflags xerces-c` 
DetSimAlg_tag=$(tag)
DETSIMALGROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DetSimAlg
DetSimAlg_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DetSimAlg
DETSIMALGVERSION=v0
DetSimAlg_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
DetSimAlg_offset=Simulation/DetSimV2
DetSimAlg_project=offline
DetSimAlg_project_release=offline_bgd
G4Svc_tag=$(tag)
G4SVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/G4Svc
G4Svc_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/G4Svc
G4SVCVERSION=v0
G4Svc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
G4Svc_offset=Simulation/DetSimV2
G4Svc_project=offline
G4Svc_project_release=offline_bgd
G4Svc_linkopts= -lG4Svc 
G4Svc_stamps=${G4SVCROOT}/${BINDIR}/G4Svc.stamp 
G4Svc_linker_library=G4Svc
DetSimAlg_linkopts= -lDetSimAlg 
DetSimAlg_stamps=${DETSIMALGROOT}/${BINDIR}/DetSimAlg.stamp 
DetSimAlg_linker_library=DetSimAlg
PMTSim_tag=$(tag)
PMTSIMROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/PMTSim
PMTSim_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/PMTSim
PMTSIMVERSION=v0
PMTSim_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
PMTSim_offset=Simulation/DetSimV2
PMTSim_project=offline
PMTSim_project_release=offline_bgd
SimUtil_tag=$(tag)
SIMUTILROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/SimUtil
SimUtil_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/SimUtil
SIMUTILVERSION=v0
SimUtil_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
SimUtil_offset=Simulation/DetSimV2
SimUtil_project=offline
SimUtil_project_release=offline_bgd
SimUtil_linkopts= -lSimUtil 
SimUtil_stamps=${SIMUTILROOT}/${BINDIR}/SimUtil.stamp 
SimUtil_linker_library=SimUtil
GenSim_tag=$(tag)
GENSIMROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/GenSim
GenSim_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/GenSim
GENSIMVERSION=v0
GenSim_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GenSim_offset=Simulation/DetSimV2
GenSim_project=offline
GenSim_project_release=offline_bgd
GenSim_cppflags= -I$(GENSIMROOT)/../PMTSim/include 
GenSim_linkopts= -lGenSim 
GenSim_stamps=${GENSIMROOT}/${BINDIR}/GenSim.stamp 
GenSim_linker_library=GenSim
EnergySpectrum_dependencies=GenSim
PMTSim_cppflags= -I$(PMTSIMROOT)/../SimUtil/include  -I$(PMTSIMROOT)/../GenSim/include 
PMTSim_linkopts= -lPMTSim 
PMTSim_stamps=${PMTSIMROOT}/${BINDIR}/PMTSim.stamp 
PMTSim_linker_library=PMTSim
DAE_tag=$(tag)
DAEROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DAE
DAE_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DAE
DAEVERSION=v0
DAE_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
DAE_offset=Simulation/DetSimV2
DAE_project=offline
DAE_project_release=offline_bgd
DAE_cppflags= -D_GEANT4_TMP_GEANT94_ 
DAE_linkopts= -lG4DAE 
DAE_stamps=${DAEROOT}/${BINDIR}/G4DAE.stamp 
DAE_linker_library=G4DAE
AnalysisCode_cppflags= -DG4DAE 
GenTools_tag=$(tag)
GENTOOLSROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/GenTools
GenTools_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/GenTools
GENTOOLSVERSION=v0
GenTools_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GenTools_offset=Simulation
GenTools_project=offline
GenTools_project_release=offline_bgd
HepMC_tag=$(tag)
HEPMCROOT=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/HepMC
HepMC_root=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface/Externals/HepMC
HEPMCVERSION=v0
HepMC_cmtpath=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
HepMC_offset=Externals
HepMC_project=ExternalInterface
HepMC_home=${JUNO_EXTLIB_HepMC_HOME}
HepMC_linkopts= -L $(HepMC_home)/lib -lHepMC 
HepMC_cppflags= -I$(HepMC_home)/include 
RandomSvc_tag=$(tag)
RANDOMSVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/CommonSvc/RandomSvc
RandomSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/CommonSvc/RandomSvc
RANDOMSVCVERSION=v0
RandomSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
RandomSvc_offset=CommonSvc
RandomSvc_project=offline
RandomSvc_project_release=offline_bgd
RandomSvc_linkopts= -lRandomSvc 
RandomSvc_stamps=${RANDOMSVCROOT}/${BINDIR}/RandomSvc.stamp 
RandomSvc_linker_library=RandomSvc
MCGlobalTimeSvc_tag=$(tag)
MCGLOBALTIMESVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/MCGlobalTimeSvc
MCGlobalTimeSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/MCGlobalTimeSvc
MCGLOBALTIMESVCVERSION=v0
MCGlobalTimeSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
MCGlobalTimeSvc_offset=Simulation/DetSimV2
MCGlobalTimeSvc_project=offline
MCGlobalTimeSvc_project_release=offline_bgd
MCGlobalTimeSvc_linkopts= -lMCGlobalTimeSvc 
MCGlobalTimeSvc_stamps=${MCGLOBALTIMESVCROOT}/${BINDIR}/MCGlobalTimeSvc.stamp 
MCGlobalTimeSvc_linker_library=MCGlobalTimeSvc
EvtNavigator_tag=$(tag)
EVTNAVIGATORROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator
EvtNavigator_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator
EVTNAVIGATORVERSION=v0
EvtNavigator_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
EvtNavigator_offset=DataModel
EvtNavigator_project=offline
EvtNavigator_project_release=offline_bgd
BaseEvent_tag=$(tag)
BASEEVENTROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent
BaseEvent_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent
BASEEVENTVERSION=v0
BaseEvent_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
BaseEvent_offset=DataModel
BaseEvent_project=offline
BaseEvent_project_release=offline_bgd
XmlObjDesc_tag=$(tag)
XMLOBJDESCROOT=/junofs/production/public/users/zhangfy/offline_bgd/XmlObjDesc
XmlObjDesc_root=/junofs/production/public/users/zhangfy/offline_bgd/XmlObjDesc
XMLOBJDESCVERSION=v0
XmlObjDesc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
XmlObjDesc_project=offline
XmlObjDesc_project_release=offline_bgd
xmlsrc=xml
XODflags= -n JM 
BaseEvent_dependencies= BaseEventObj2Doth  BaseEventDict  BaseEventxodsrc 
install_more_includes_dependencies= BaseEventObj2Doth 
BaseEventDict_dependencies= BaseEventObj2Doth  install_more_includes 
BaseEventxodsrc_dependencies= BaseEventObj2Doth 
BaseEvent_linkopts= -lBaseEvent 
BaseEvent_stamps=${BASEEVENTROOT}/${BINDIR}/BaseEvent.stamp 
BaseEvent_linker_library=BaseEvent
EDMUtil_tag=$(tag)
EDMUTILROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil
EDMUtil_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil
EDMUTILVERSION=v0
EDMUtil_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
EDMUtil_offset=DataModel
EDMUtil_project=offline
EDMUtil_project_release=offline_bgd
EDMUtil_dependencies= EDMUtilDict  EDMUtilDict  EDMUtilDict  EDMUtilDict 
EDMUtilDict_dependencies= EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes  EDMUtilObj2Doth  install_more_includes 
EDMUtil_linkopts= -lEDMUtil 
EDMUtil_stamps=${EDMUTILROOT}/${BINDIR}/EDMUtil.stamp 
EDMUtil_linker_library=EDMUtil
EvtNavigator_cintflags=-I$(CMTINSTALLAREA)/include
EvtNavigator_dependencies= EvtNavigatorDict 
EvtNavigatorDict_dependencies= EvtNavigatorObj2Doth  install_more_includes 
EvtNavigator_linkopts= -lEvtNavigator 
EvtNavigator_stamps=${EVTNAVIGATORROOT}/${BINDIR}/EvtNavigator.stamp 
EvtNavigator_linker_library=EvtNavigator
GenEventV2_tag=$(tag)
GENEVENTV2ROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2
GenEventV2_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2
GENEVENTV2VERSION=v0
GenEventV2_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
GenEventV2_offset=DataModel
GenEventV2_project=offline
GenEventV2_project_release=offline_bgd
GenHeader_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT)  $(HepMC_cppflags) 
GenEvent_cintflags= -p  -I$(GENEVENTV2ROOT)  -I$(BASEEVENTROOT)  $(HepMC_cppflags) 
GenEventV2_dependencies= GenEventV2Dict 
GenEventV2Dict_dependencies= GenEventV2Obj2Doth  install_more_includes 
GenEventV2_linkopts= -lGenEventV2 
GenEventV2_stamps=${GENEVENTV2ROOT}/${BINDIR}/GenEventV2.stamp 
GenEventV2_linker_library=GenEventV2
GenTools_use_linkopts= -lEG 
GenTools_linkopts= -lGenTools 
GenTools_stamps=${GENTOOLSROOT}/${BINDIR}/GenTools.stamp 
GenTools_linker_library=GenTools
JunoTimer_tag=$(tag)
JUNOTIMERROOT=/junofs/production/public/users/zhangfy/offline_bgd/Utilities/JunoTimer
JunoTimer_root=/junofs/production/public/users/zhangfy/offline_bgd/Utilities/JunoTimer
JUNOTIMERVERSION=v0
JunoTimer_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
JunoTimer_offset=Utilities
JunoTimer_project=offline
JunoTimer_project_release=offline_bgd
JunoTimer_linkopts= -lJunoTimer 
JunoTimer_stamps=${JUNOTIMERROOT}/${BINDIR}/JunoTimer.stamp 
JunoTimer_linker_library=JunoTimer
DataRegistritionSvc_tag=$(tag)
DATAREGISTRITIONSVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/DataRegistritionSvc
DataRegistritionSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/DataRegistritionSvc
DATAREGISTRITIONSVCVERSION=v0
DataRegistritionSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
DataRegistritionSvc_offset=DataModel
DataRegistritionSvc_project=offline
DataRegistritionSvc_project_release=offline_bgd
DataRegistritionSvc_linkopts= -lDataRegistritionSvc 
DataRegistritionSvc_stamps=${DATAREGISTRITIONSVCROOT}/${BINDIR}/DataRegistritionSvc.stamp 
DataRegistritionSvc_linker_library=DataRegistritionSvc
SimEventV2_tag=$(tag)
SIMEVENTV2ROOT=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/SimEventV2
SimEventV2_root=/junofs/production/public/users/zhangfy/offline_bgd/DataModel/SimEventV2
SIMEVENTV2VERSION=v0
SimEventV2_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
SimEventV2_offset=DataModel
SimEventV2_project=offline
SimEventV2_project_release=offline_bgd
SimEventV2_cintflags= -I$(SIMEVENTV2ROOT)  -I$(BASEEVENTROOT)  -I$(EDMUTILROOT) 
SimHeader_cintflags= $(SimEventV2_cintflags) 
SimPMTHit_cintflags= $(SimEventV2_cintflags) 
SimTrack_cintflags= $(SimEventV2_cintflags) 
SimEvent_cintflags= $(SimEventV2_cintflags) 
SimTTHit_cintflags= $(SimEventV2_cintflags) 
SimEventV2_dependencies= SimEventV2Dict  SimEventV2Dict  SimEventV2Dict  SimEventV2Dict  SimEventV2Dict 
SimEventV2Dict_dependencies= SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes  SimEventV2Obj2Doth  install_more_includes 
SimEventV2_linkopts= -lSimEventV2 
SimEventV2_stamps=${SIMEVENTV2ROOT}/${BINDIR}/SimEventV2.stamp 
SimEventV2_linker_library=SimEventV2
test_SimEvent_write_dependencies=SimEventV2
test_SimEvent_read_dependencies=SimEventV2
RootIOSvc_tag=$(tag)
ROOTIOSVCROOT=/junofs/production/public/users/zhangfy/offline_bgd/RootIO/RootIOSvc
RootIOSvc_root=/junofs/production/public/users/zhangfy/offline_bgd/RootIO/RootIOSvc
ROOTIOSVCVERSION=v0
RootIOSvc_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
RootIOSvc_offset=RootIO
RootIOSvc_project=offline
RootIOSvc_project_release=offline_bgd
RootIOUtil_tag=$(tag)
ROOTIOUTILROOT=/junofs/production/public/users/zhangfy/offline_bgd/RootIO/RootIOUtil
RootIOUtil_root=/junofs/production/public/users/zhangfy/offline_bgd/RootIO/RootIOUtil
ROOTIOUTILVERSION=v0
RootIOUtil_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
RootIOUtil_offset=RootIO
RootIOUtil_project=offline
RootIOUtil_project_release=offline_bgd
RootIOUtil_linkopts= -lRootIOUtil 
RootIOUtil_stamps=${ROOTIOUTILROOT}/${BINDIR}/RootIOUtil.stamp 
RootIOUtil_linker_library=RootIOUtil
RootIOSvc_linkopts= -lRootIOSvc 
RootIOSvc_stamps=${ROOTIOSVCROOT}/${BINDIR}/RootIOSvc.stamp 
RootIOSvc_linker_library=RootIOSvc
Geometry_tag=$(tag)
GEOMETRYROOT=/junofs/production/public/users/zhangfy/offline_bgd/Detector/Geometry
Geometry_root=/junofs/production/public/users/zhangfy/offline_bgd/Detector/Geometry
GEOMETRYVERSION=v0
Geometry_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Geometry_offset=Detector
Geometry_project=offline
Geometry_project_release=offline_bgd
Identifier_tag=$(tag)
IDENTIFIERROOT=/junofs/production/public/users/zhangfy/offline_bgd/Detector/Identifier
Identifier_root=/junofs/production/public/users/zhangfy/offline_bgd/Detector/Identifier
IDENTIFIERVERSION=v0
Identifier_cmtpath=/junofs/production/public/users/zhangfy/offline_bgd
Identifier_offset=Detector
Identifier_project=offline
Identifier_project_release=offline_bgd
Identifier_linkopts= -lIdentifier 
Identifier_stamps=${IDENTIFIERROOT}/${BINDIR}/Identifier.stamp 
Identifier_linker_library=Identifier
JUNO_GEOMETRY_PATH=/junofs/production/public/users/zhangfy/offline_bgd/Detector/Geometry
Geometry_linkopts= -lGeometry 
Geometry_stamps=${GEOMETRYROOT}/${BINDIR}/Geometry.stamp 
Geometry_linker_library=Geometry
AnalysisCode_linkopts= -lAnalysisCode 
AnalysisCode_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(AnalysisCode_use_linkopts)
AnalysisCode_use_linkopts=    $(PMTSim_linkopts)  $(SimUtil_linkopts)  $(DetSimAlg_linkopts)  $(GenSim_linkopts)  $(JunoTimer_linkopts)  $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(DummyAlg_linkopts)  $(GenTools_linkopts)  $(RootWriter_linkopts)  $(G4Svc_linkopts)  $(RandomSvc_linkopts)  $(MCGlobalTimeSvc_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(GenEventV2_linkopts)  $(DataRegistritionSvc_linkopts)  $(SimEventV2_linkopts)  $(EDMUtil_linkopts)  $(Geometry_linkopts)  $(Identifier_linkopts)  $(SniperKernel_linkopts)  $(DAE_linkopts)  $(BaseEvent_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(DetSimPolicy_linkopts)  $(Geant4_linkopts)  $(CLHEP_linkopts)  $(Xercesc_linkopts)  $(HepMC_linkopts) 
AnalysisCode_stamps=${ANALYSISCODEROOT}/${BINDIR}/AnalysisCode.stamp 
AnalysisCode_linker_library=AnalysisCode
tag=amd64_linux26
package=AnalysisCode
version=v0
PACKAGE_ROOT=$(ANALYSISCODEROOT)
srcdir=../src
bin=../$(AnalysisCode_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/AnalysisCode/amd64_linux26/
project=offline
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(AnalysisCode_linkopts)  $(PMTSim_linkopts)  $(SimUtil_linkopts)  $(DetSimAlg_linkopts)  $(GenSim_linkopts)  $(JunoTimer_linkopts)  $(SniperRelease_linkopts)  $(DataBuffer_linkopts)  $(HelloWorld_linkopts)  $(DummyAlg_linkopts)  $(GenTools_linkopts)  $(RootWriter_linkopts)  $(G4Svc_linkopts)  $(RandomSvc_linkopts)  $(MCGlobalTimeSvc_linkopts)  $(RootIOSvc_linkopts)  $(RootIOUtil_linkopts)  $(EvtNavigator_linkopts)  $(GenEventV2_linkopts)  $(DataRegistritionSvc_linkopts)  $(SimEventV2_linkopts)  $(EDMUtil_linkopts)  $(Geometry_linkopts)  $(Identifier_linkopts)  $(SniperKernel_linkopts)  $(DAE_linkopts)  $(BaseEvent_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(ROOT_linkopts)  $(DetSimPolicy_linkopts)  $(Geant4_linkopts)  $(CLHEP_linkopts)  $(Xercesc_linkopts)  $(HepMC_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/junofs/production/public/users/zhangfy/offline_bgd/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/InstallArea/${CMTCONFIG}/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-cpp/1.1.8/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/mysql-connector-c/6.1.9/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/libmore/0.8.3/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/lib/geant4-9.4.4/Linux-g++:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/CLHEP/2.1.0.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Geant4/9.4.p04/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/HepMC/2.06.09/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/CLHEP/2.1.0.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/fftw3/3.2.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/gsl/1.16/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Xercesc/3.1.1/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/lib:/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Python/2.7.6/lib:/junofs/production/public/users/zhangfy/local/matlab/bin/glnxa64:/junofs/production/public/users/zhangfy/local/matlab/sys/os/glnxa64:/usr/lib64/classads:/usr/lib64:/usr/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
cmt_installarea_linkopts= -L/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalInterface
sniper_home=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper
offline_home=/junofs/production/public/users/zhangfy/offline_bgd
offline_install_include= /junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/include 
sniper_install_include= /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/$(tag)/lib
offline_python_path=/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/$(tag)/lib
sniper_install_python=/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/sniper/$(sniper_installarea_prefix)/python
offline_install_python=/junofs/production/public/users/zhangfy/offline_bgd/$(offline_installarea_prefix)/python
CMTINSTALLAREA=/junofs/production/public/users/zhangfy/offline_bgd/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(PMTSim_root)/cmt/requirements $(SimUtil_root)/cmt/requirements $(DetSimAlg_root)/cmt/requirements $(GenSim_root)/cmt/requirements $(JunoTimer_root)/cmt/requirements $(SniperRelease_root)/cmt/requirements $(DataBuffer_root)/cmt/requirements $(HelloWorld_root)/cmt/requirements $(DummyAlg_root)/cmt/requirements $(GenTools_root)/cmt/requirements $(RootWriter_root)/cmt/requirements $(G4Svc_root)/cmt/requirements $(RandomSvc_root)/cmt/requirements $(MCGlobalTimeSvc_root)/cmt/requirements $(RootIOSvc_root)/cmt/requirements $(RootIOUtil_root)/cmt/requirements $(EvtNavigator_root)/cmt/requirements $(GenEventV2_root)/cmt/requirements $(DataRegistritionSvc_root)/cmt/requirements $(SimEventV2_root)/cmt/requirements $(EDMUtil_root)/cmt/requirements $(Geometry_root)/cmt/requirements $(Identifier_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(DAE_root)/cmt/requirements $(BaseEvent_root)/cmt/requirements $(XmlObjDesc_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(DetSimPolicy_root)/cmt/requirements $(Geant4_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(Xercesc_root)/cmt/requirements $(HepMC_root)/cmt/requirements 
use_includes= $(ppcmd)"$(PMTSim_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/PMTSim/include" $(ppcmd)"$(SimUtil_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/SimUtil/include" $(ppcmd)"$(DetSimAlg_root)/src" $(ppcmd)"$(GenSim_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/GenSim/include" $(ppcmd)"$(JunoTimer_root)/src" $(ppcmd)"$(SniperRelease_root)/src" $(ppcmd)"$(DataBuffer_root)/src" $(ppcmd)"$(HelloWorld_root)/src" $(ppcmd)"$(DummyAlg_root)/src" $(ppcmd)"$(GenTools_root)/src" $(ppcmd)"$(RootWriter_root)/src" $(ppcmd)"$(G4Svc_root)/src" $(ppcmd)"$(RandomSvc_root)/src" $(ppcmd)"$(MCGlobalTimeSvc_root)/src" $(ppcmd)"$(RootIOSvc_root)/src" $(ppcmd)"$(RootIOUtil_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/RootIO/RootIOUtil/RootIOUtil" $(ppcmd)"$(EvtNavigator_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EvtNavigator/EvtNavigator" $(ppcmd)"$(GenEventV2_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2/" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/GenEventV2/Event" $(ppcmd)"$(DataRegistritionSvc_root)/src" $(ppcmd)"$(SimEventV2_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/SimEventV2/" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/SimEventV2/Event" $(ppcmd)"$(EDMUtil_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil/include" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/EDMUtil/EDMUtil" $(ppcmd)"$(Geometry_root)/src" $(ppcmd)"$(Identifier_root)/src" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(DAE_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/share/geant4-9.4.4" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/Simulation/DetSimV2/DAE/include" $(ppcmd)"$(BaseEvent_root)/src" $(ppcmd)"/junofs/production/public/users/zhangfy/offline_bgd/DataModel/BaseEvent/Event" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/Boost/1.55.0/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/include" $(ppcmd)"$(DetSimPolicy_root)/src" $(ppcmd)"$(Geant4_root)/src" $(ppcmd)"/cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/include/geant4" $(ppcmd)"$(CLHEP_root)/src" $(ppcmd)"$(Xercesc_root)/src" $(ppcmd)"$(HepMC_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(AnalysisCode_stamps)  $(PMTSim_stamps)  $(SimUtil_stamps)  $(DetSimAlg_stamps)  $(GenSim_stamps)  $(JunoTimer_stamps)  $(SniperRelease_stamps)  $(DataBuffer_stamps)  $(HelloWorld_stamps)  $(DummyAlg_stamps)  $(GenTools_stamps)  $(RootWriter_stamps)  $(G4Svc_stamps)  $(RandomSvc_stamps)  $(MCGlobalTimeSvc_stamps)  $(RootIOSvc_stamps)  $(RootIOUtil_stamps)  $(EvtNavigator_stamps)  $(GenEventV2_stamps)  $(DataRegistritionSvc_stamps)  $(SimEventV2_stamps)  $(EDMUtil_stamps)  $(Geometry_stamps)  $(Identifier_stamps)  $(SniperKernel_stamps)  $(DAE_stamps)  $(BaseEvent_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps)  $(ROOT_stamps)  $(DetSimPolicy_stamps)  $(Geant4_stamps)  $(CLHEP_stamps)  $(Xercesc_stamps)  $(HepMC_stamps) 
use_cflags=  $(AnalysisCode_cflags)  $(PMTSim_cflags)  $(SimUtil_cflags)  $(DetSimAlg_cflags)  $(GenSim_cflags)  $(JunoTimer_cflags)  $(SniperRelease_cflags)  $(DataBuffer_cflags)  $(HelloWorld_cflags)  $(DummyAlg_cflags)  $(GenTools_cflags)  $(RootWriter_cflags)  $(G4Svc_cflags)  $(RandomSvc_cflags)  $(MCGlobalTimeSvc_cflags)  $(RootIOSvc_cflags)  $(RootIOUtil_cflags)  $(EvtNavigator_cflags)  $(GenEventV2_cflags)  $(DataRegistritionSvc_cflags)  $(SimEventV2_cflags)  $(EDMUtil_cflags)  $(Geometry_cflags)  $(Identifier_cflags)  $(SniperKernel_cflags)  $(DAE_cflags)  $(BaseEvent_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags)  $(ROOT_cflags)  $(DetSimPolicy_cflags)  $(Geant4_cflags)  $(CLHEP_cflags)  $(Xercesc_cflags)  $(HepMC_cflags) 
use_pp_cflags=  $(AnalysisCode_pp_cflags)  $(PMTSim_pp_cflags)  $(SimUtil_pp_cflags)  $(DetSimAlg_pp_cflags)  $(GenSim_pp_cflags)  $(JunoTimer_pp_cflags)  $(SniperRelease_pp_cflags)  $(DataBuffer_pp_cflags)  $(HelloWorld_pp_cflags)  $(DummyAlg_pp_cflags)  $(GenTools_pp_cflags)  $(RootWriter_pp_cflags)  $(G4Svc_pp_cflags)  $(RandomSvc_pp_cflags)  $(MCGlobalTimeSvc_pp_cflags)  $(RootIOSvc_pp_cflags)  $(RootIOUtil_pp_cflags)  $(EvtNavigator_pp_cflags)  $(GenEventV2_pp_cflags)  $(DataRegistritionSvc_pp_cflags)  $(SimEventV2_pp_cflags)  $(EDMUtil_pp_cflags)  $(Geometry_pp_cflags)  $(Identifier_pp_cflags)  $(SniperKernel_pp_cflags)  $(DAE_pp_cflags)  $(BaseEvent_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(ROOT_pp_cflags)  $(DetSimPolicy_pp_cflags)  $(Geant4_pp_cflags)  $(CLHEP_pp_cflags)  $(Xercesc_pp_cflags)  $(HepMC_pp_cflags) 
use_cppflags=  $(AnalysisCode_cppflags)  $(PMTSim_cppflags)  $(SimUtil_cppflags)  $(DetSimAlg_cppflags)  $(GenSim_cppflags)  $(JunoTimer_cppflags)  $(SniperRelease_cppflags)  $(DataBuffer_cppflags)  $(HelloWorld_cppflags)  $(DummyAlg_cppflags)  $(GenTools_cppflags)  $(RootWriter_cppflags)  $(G4Svc_cppflags)  $(RandomSvc_cppflags)  $(MCGlobalTimeSvc_cppflags)  $(RootIOSvc_cppflags)  $(RootIOUtil_cppflags)  $(EvtNavigator_cppflags)  $(GenEventV2_cppflags)  $(DataRegistritionSvc_cppflags)  $(SimEventV2_cppflags)  $(EDMUtil_cppflags)  $(Geometry_cppflags)  $(Identifier_cppflags)  $(SniperKernel_cppflags)  $(DAE_cppflags)  $(BaseEvent_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(ROOT_cppflags)  $(DetSimPolicy_cppflags)  $(Geant4_cppflags)  $(CLHEP_cppflags)  $(Xercesc_cppflags)  $(HepMC_cppflags) 
use_pp_cppflags=  $(AnalysisCode_pp_cppflags)  $(PMTSim_pp_cppflags)  $(SimUtil_pp_cppflags)  $(DetSimAlg_pp_cppflags)  $(GenSim_pp_cppflags)  $(JunoTimer_pp_cppflags)  $(SniperRelease_pp_cppflags)  $(DataBuffer_pp_cppflags)  $(HelloWorld_pp_cppflags)  $(DummyAlg_pp_cppflags)  $(GenTools_pp_cppflags)  $(RootWriter_pp_cppflags)  $(G4Svc_pp_cppflags)  $(RandomSvc_pp_cppflags)  $(MCGlobalTimeSvc_pp_cppflags)  $(RootIOSvc_pp_cppflags)  $(RootIOUtil_pp_cppflags)  $(EvtNavigator_pp_cppflags)  $(GenEventV2_pp_cppflags)  $(DataRegistritionSvc_pp_cppflags)  $(SimEventV2_pp_cppflags)  $(EDMUtil_pp_cppflags)  $(Geometry_pp_cppflags)  $(Identifier_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(DAE_pp_cppflags)  $(BaseEvent_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(ROOT_pp_cppflags)  $(DetSimPolicy_pp_cppflags)  $(Geant4_pp_cppflags)  $(CLHEP_pp_cppflags)  $(Xercesc_pp_cppflags)  $(HepMC_pp_cppflags) 
use_fflags=  $(AnalysisCode_fflags)  $(PMTSim_fflags)  $(SimUtil_fflags)  $(DetSimAlg_fflags)  $(GenSim_fflags)  $(JunoTimer_fflags)  $(SniperRelease_fflags)  $(DataBuffer_fflags)  $(HelloWorld_fflags)  $(DummyAlg_fflags)  $(GenTools_fflags)  $(RootWriter_fflags)  $(G4Svc_fflags)  $(RandomSvc_fflags)  $(MCGlobalTimeSvc_fflags)  $(RootIOSvc_fflags)  $(RootIOUtil_fflags)  $(EvtNavigator_fflags)  $(GenEventV2_fflags)  $(DataRegistritionSvc_fflags)  $(SimEventV2_fflags)  $(EDMUtil_fflags)  $(Geometry_fflags)  $(Identifier_fflags)  $(SniperKernel_fflags)  $(DAE_fflags)  $(BaseEvent_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags)  $(ROOT_fflags)  $(DetSimPolicy_fflags)  $(Geant4_fflags)  $(CLHEP_fflags)  $(Xercesc_fflags)  $(HepMC_fflags) 
use_pp_fflags=  $(AnalysisCode_pp_fflags)  $(PMTSim_pp_fflags)  $(SimUtil_pp_fflags)  $(DetSimAlg_pp_fflags)  $(GenSim_pp_fflags)  $(JunoTimer_pp_fflags)  $(SniperRelease_pp_fflags)  $(DataBuffer_pp_fflags)  $(HelloWorld_pp_fflags)  $(DummyAlg_pp_fflags)  $(GenTools_pp_fflags)  $(RootWriter_pp_fflags)  $(G4Svc_pp_fflags)  $(RandomSvc_pp_fflags)  $(MCGlobalTimeSvc_pp_fflags)  $(RootIOSvc_pp_fflags)  $(RootIOUtil_pp_fflags)  $(EvtNavigator_pp_fflags)  $(GenEventV2_pp_fflags)  $(DataRegistritionSvc_pp_fflags)  $(SimEventV2_pp_fflags)  $(EDMUtil_pp_fflags)  $(Geometry_pp_fflags)  $(Identifier_pp_fflags)  $(SniperKernel_pp_fflags)  $(DAE_pp_fflags)  $(BaseEvent_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(ROOT_pp_fflags)  $(DetSimPolicy_pp_fflags)  $(Geant4_pp_fflags)  $(CLHEP_pp_fflags)  $(Xercesc_pp_fflags)  $(HepMC_pp_fflags) 
use_libraries= $(PMTSim_libraries)  $(SimUtil_libraries)  $(DetSimAlg_libraries)  $(GenSim_libraries)  $(JunoTimer_libraries)  $(SniperRelease_libraries)  $(DataBuffer_libraries)  $(HelloWorld_libraries)  $(DummyAlg_libraries)  $(GenTools_libraries)  $(RootWriter_libraries)  $(G4Svc_libraries)  $(RandomSvc_libraries)  $(MCGlobalTimeSvc_libraries)  $(RootIOSvc_libraries)  $(RootIOUtil_libraries)  $(EvtNavigator_libraries)  $(GenEventV2_libraries)  $(DataRegistritionSvc_libraries)  $(SimEventV2_libraries)  $(EDMUtil_libraries)  $(Geometry_libraries)  $(Identifier_libraries)  $(SniperKernel_libraries)  $(DAE_libraries)  $(BaseEvent_libraries)  $(XmlObjDesc_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries)  $(ROOT_libraries)  $(DetSimPolicy_libraries)  $(Geant4_libraries)  $(CLHEP_libraries)  $(Xercesc_libraries)  $(HepMC_libraries) 
fincludes= $(includes)
AnalysisCode_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= AnalysisCode 
all_constituents= $(constituents)
constituentsclean= AnalysisCodeclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
AnalysisCodeprototype_dependencies= $(AnalysisCodecompile_dependencies)
