/********************************************************************
* ../src/CalibEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/CalibEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCalibEventDict();
extern void G__cpp_setup_inheritanceCalibEventDict();
extern void G__cpp_setup_typetableCalibEventDict();
extern void G__cpp_setup_memvarCalibEventDict();
extern void G__cpp_setup_globalCalibEventDict();
extern void G__cpp_setup_memfuncCalibEventDict();
extern void G__cpp_setup_funcCalibEventDict();
extern void G__set_cpp_environmentCalibEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CalibEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CalibEventDictLN_TClass;
extern G__linked_taginfo G__CalibEventDictLN_TBuffer;
extern G__linked_taginfo G__CalibEventDictLN_TMemberInspector;
extern G__linked_taginfo G__CalibEventDictLN_TObject;
extern G__linked_taginfo G__CalibEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CalibEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CalibEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibEventDictLN_JM;
extern G__linked_taginfo G__CalibEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__CalibEventDictLN_JMcLcLCalibPMTChannel;
extern G__linked_taginfo G__CalibEventDictLN_JMcLcLCalibEvent;
extern G__linked_taginfo G__CalibEventDictLN_listlEJMcLcLCalibPMTChannelmUcOallocatorlEJMcLcLCalibPMTChannelmUgRsPgR;

/* STUB derived class for protected member access */
