//
// File generated by /cvmfs/juno.ihep.ac.cn/sl6_amd64_gcc447/Pre-Release/J18v1r1-Pre1/ExternalLibs/ROOT/5.34.11/bin/rootcint at Thu Dec 28 13:42:14 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIsrcdICalibHeaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CalibHeaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JMcLcLCalibHeader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JMcLcLCalibHeader(void *p = 0);
   static void *newArray_JMcLcLCalibHeader(Long_t size, void *p);
   static void delete_JMcLcLCalibHeader(void *p);
   static void deleteArray_JMcLcLCalibHeader(void *p);
   static void destruct_JMcLcLCalibHeader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JM::CalibHeader*)
   {
      ::JM::CalibHeader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JM::CalibHeader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JM::CalibHeader", ::JM::CalibHeader::Class_Version(), "./CalibHeader.h", 41,
                  typeid(::JM::CalibHeader), DefineBehavior(ptr, ptr),
                  &::JM::CalibHeader::Dictionary, isa_proxy, 4,
                  sizeof(::JM::CalibHeader) );
      instance.SetNew(&new_JMcLcLCalibHeader);
      instance.SetNewArray(&newArray_JMcLcLCalibHeader);
      instance.SetDelete(&delete_JMcLcLCalibHeader);
      instance.SetDeleteArray(&deleteArray_JMcLcLCalibHeader);
      instance.SetDestructor(&destruct_JMcLcLCalibHeader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JM::CalibHeader*)
   {
      return GenerateInitInstanceLocal((::JM::CalibHeader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JM::CalibHeader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace JM {
//______________________________________________________________________________
TClass *CalibHeader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CalibHeader::Class_Name()
{
   return "JM::CalibHeader";
}

//______________________________________________________________________________
const char *CalibHeader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::CalibHeader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CalibHeader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JM::CalibHeader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CalibHeader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::CalibHeader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CalibHeader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JM::CalibHeader*)0x0)->GetClass();
   return fgIsA;
}

} // namespace JM
      namespace JM {
//______________________________________________________________________________
void CalibHeader::Streamer(TBuffer &R__b)
{
   // Stream an object of class JM::CalibHeader.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JM::CalibHeader::Class(),this);
   } else {
      R__b.WriteClassBuffer(JM::CalibHeader::Class(),this);
   }
}

} // namespace JM
//______________________________________________________________________________
      namespace JM {
void CalibHeader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JM::CalibHeader.
      TClass *R__cl = ::JM::CalibHeader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_event", &m_event);
      R__insp.InspectMember(m_event, "m_event.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_TTEvent", &m_TTEvent);
      R__insp.InspectMember(m_TTEvent, "m_TTEvent.");
      //This works around a msvc bug and should be harmless on other platforms
      typedef JM::HeaderObject baseClass1;
      baseClass1::ShowMembers(R__insp);
}

} // namespace JM
namespace ROOT {
   // Wrappers around operator new
   static void *new_JMcLcLCalibHeader(void *p) {
      return  p ? new(p) ::JM::CalibHeader : new ::JM::CalibHeader;
   }
   static void *newArray_JMcLcLCalibHeader(Long_t nElements, void *p) {
      return p ? new(p) ::JM::CalibHeader[nElements] : new ::JM::CalibHeader[nElements];
   }
   // Wrapper around operator delete
   static void delete_JMcLcLCalibHeader(void *p) {
      delete ((::JM::CalibHeader*)p);
   }
   static void deleteArray_JMcLcLCalibHeader(void *p) {
      delete [] ((::JM::CalibHeader*)p);
   }
   static void destruct_JMcLcLCalibHeader(void *p) {
      typedef ::JM::CalibHeader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JM::CalibHeader

/********************************************************
* ../src/CalibHeaderDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCalibHeaderDict();

extern "C" void G__set_cpp_environmentCalibHeaderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CalibHeader.h");
  G__cpp_reset_tagtableCalibHeaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevCalibHeaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JM::CalibHeader */
static int G__CalibHeaderDict_207_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::CalibHeader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::CalibHeader[n];
     } else {
       p = new((void*) gvp) JM::CalibHeader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JM::CalibHeader;
     } else {
       p = new((void*) gvp) JM::CalibHeader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::CalibHeader*) G__getstructoffset())->getCalibPmtChannel((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::CalibHeader*) G__getstructoffset())->addCalibPmtChannel((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::CalibHeader*) G__getstructoffset())->event());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::CalibHeader*) G__getstructoffset())->setEvent((JM::CalibEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JM::CalibHeader*) G__getstructoffset())->ttEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::CalibHeader*) G__getstructoffset())->setTTEvent((JM::TTCalibEvent*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JM::CalibHeader*) G__getstructoffset())->hasEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JM::CalibHeader*) G__getstructoffset())->hasTTEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JM::CalibHeader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::CalibHeader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JM::CalibHeader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JM::CalibHeader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JM::CalibHeader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::CalibHeader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::CalibHeader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JM::CalibHeader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibHeaderDict_207_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JM::CalibHeader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__CalibHeaderDict_207_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JM::CalibHeader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JM::CalibHeader(*(JM::CalibHeader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JM::CalibHeader G__TJMcLcLCalibHeader;
static int G__CalibHeaderDict_207_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JM::CalibHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JM::CalibHeader*) (soff+(sizeof(JM::CalibHeader)*i)))->~G__TJMcLcLCalibHeader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JM::CalibHeader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JM::CalibHeader*) (soff))->~G__TJMcLcLCalibHeader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__CalibHeaderDict_207_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JM::CalibHeader* dest = (JM::CalibHeader*) G__getstructoffset();
   *dest = *(JM::CalibHeader*) libp->para[0].ref;
   const JM::CalibHeader& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JM::CalibHeader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCalibHeaderDict {
 public:
  G__Sizep2memfuncCalibHeaderDict(): p(&G__Sizep2memfuncCalibHeaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCalibHeaderDict::*p)();
};

size_t G__get_sizep2memfuncCalibHeaderDict()
{
  G__Sizep2memfuncCalibHeaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCalibHeaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader))) {
     JM::CalibHeader *G__Lderived;
     G__Lderived=(JM::CalibHeader*)0x1000;
     {
       JM::HeaderObject *G__Lpbase=(JM::HeaderObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader),G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLHeaderObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       JM::EventObject *G__Lpbase=(JM::EventObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader),G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLEventObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader),G__get_linked_tagnum(&G__CalibHeaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCalibHeaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<JM::CalibPMTChannel*>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_listlEJMcLcLCalibPMTChannelmUcOallocatorlEJMcLcLCalibPMTChannelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<JM::CalibTTChannel*>",117,G__get_linked_tagnum(&G__CalibHeaderDictLN_listlEJMcLcLCalibTTChannelmUcOallocatorlEJMcLcLCalibTTChannelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JM::CalibHeader */
static void G__setup_memvarJMcLcLCalibHeader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader));
   { JM::CalibHeader *p; p=(JM::CalibHeader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLSmartRef),-1,-1,4,"m_event=",0,"||Smart pointer to the CalibEvent");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLSmartRef),-1,-1,4,"m_TTEvent=",0,"||Smart pointer to the TTCalibEvent");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CalibHeaderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCalibHeaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJMcLcLCalibHeader(void) {
   /* JM::CalibHeader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader));
   G__memfunc_setup("CalibHeader",1060,G__CalibHeaderDict_207_0_1, 105, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getCalibPmtChannel",1797,G__CalibHeaderDict_207_0_2, 85, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibPMTChannel), -1, 0, 1, 1, 1, 1, "h - - 0 - pmtid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addCalibPmtChannel",1774,G__CalibHeaderDict_207_0_3, 85, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibPMTChannel), -1, 0, 1, 1, 1, 0, "h - - 0 - pmtid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("event",546,G__CalibHeaderDict_207_0_4, 85, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEvent",846,G__CalibHeaderDict_207_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JM::CalibEvent' - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ttEvent",746,G__CalibHeaderDict_207_0_6, 85, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLTTCalibEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTTEvent",1014,G__CalibHeaderDict_207_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "U 'JM::TTCalibEvent' - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEventEntry",1376,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - eventName n - 'Long64_t' 1 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("event",546,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLEventObject), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - eventName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("hasEvent",830,G__CalibHeaderDict_207_0_10, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("hasTTEvent",998,G__CalibHeaderDict_207_0_11, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__CalibHeaderDict_207_0_12, 85, G__get_linked_tagnum(&G__CalibHeaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JM::CalibHeader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CalibHeaderDict_207_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::CalibHeader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CalibHeaderDict_207_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JM::CalibHeader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CalibHeaderDict_207_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JM::CalibHeader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibHeaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CalibHeaderDict_207_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CalibHeaderDict_207_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::CalibHeader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CalibHeaderDict_207_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::CalibHeader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CalibHeaderDict_207_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JM::CalibHeader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CalibHeaderDict_207_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JM::CalibHeader::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CalibHeader", 1060, G__CalibHeaderDict_207_0_24, (int) ('i'), G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader), -1, 0, 1, 1, 1, 0, "u 'JM::CalibHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CalibHeader", 1186, G__CalibHeaderDict_207_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__CalibHeaderDict_207_0_26, (int) ('u'), G__get_linked_tagnum(&G__CalibHeaderDictLN_JMcLcLCalibHeader), -1, 1, 1, 1, 1, 0, "u 'JM::CalibHeader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCalibHeaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCalibHeaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCalibHeaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CalibHeaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JM = { "JM" , 110 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLEventObject = { "JM::EventObject" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLHeaderObject = { "JM::HeaderObject" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLCalibPMTChannel = { "JM::CalibPMTChannel" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLCalibEvent = { "JM::CalibEvent" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_listlEJMcLcLCalibPMTChannelmUcOallocatorlEJMcLcLCalibPMTChannelmUgRsPgR = { "list<JM::CalibPMTChannel*,allocator<JM::CalibPMTChannel*> >" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLTTCalibEvent = { "JM::TTCalibEvent" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_listlEJMcLcLCalibTTChannelmUcOallocatorlEJMcLcLCalibTTChannelmUgRsPgR = { "list<JM::CalibTTChannel*,allocator<JM::CalibTTChannel*> >" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLSmartRef = { "JM::SmartRef" , 99 , -1 };
G__linked_taginfo G__CalibHeaderDictLN_JMcLcLCalibHeader = { "JM::CalibHeader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCalibHeaderDict() {
  G__CalibHeaderDictLN_TClass.tagnum = -1 ;
  G__CalibHeaderDictLN_TBuffer.tagnum = -1 ;
  G__CalibHeaderDictLN_TMemberInspector.tagnum = -1 ;
  G__CalibHeaderDictLN_TObject.tagnum = -1 ;
  G__CalibHeaderDictLN_string.tagnum = -1 ;
  G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CalibHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CalibHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibHeaderDictLN_JM.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLEventObject.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLHeaderObject.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLCalibPMTChannel.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLCalibEvent.tagnum = -1 ;
  G__CalibHeaderDictLN_listlEJMcLcLCalibPMTChannelmUcOallocatorlEJMcLcLCalibPMTChannelmUgRsPgR.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLTTCalibEvent.tagnum = -1 ;
  G__CalibHeaderDictLN_listlEJMcLcLCalibTTChannelmUcOallocatorlEJMcLcLCalibTTChannelmUgRsPgR.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLSmartRef.tagnum = -1 ;
  G__CalibHeaderDictLN_JMcLcLCalibHeader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCalibHeaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_string);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JM);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLEventObject);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLHeaderObject);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLCalibPMTChannel);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLCalibEvent);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_listlEJMcLcLCalibPMTChannelmUcOallocatorlEJMcLcLCalibPMTChannelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLTTCalibEvent);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_listlEJMcLcLCalibTTChannelmUcOallocatorlEJMcLcLCalibTTChannelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLSmartRef);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CalibHeaderDictLN_JMcLcLCalibHeader),sizeof(JM::CalibHeader),-1,292096,(char*)NULL,G__setup_memvarJMcLcLCalibHeader,G__setup_memfuncJMcLcLCalibHeader);
}
extern "C" void G__cpp_setupCalibHeaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCalibHeaderDict()");
  G__set_cpp_environmentCalibHeaderDict();
  G__cpp_setup_tagtableCalibHeaderDict();

  G__cpp_setup_inheritanceCalibHeaderDict();

  G__cpp_setup_typetableCalibHeaderDict();

  G__cpp_setup_memvarCalibHeaderDict();

  G__cpp_setup_memfuncCalibHeaderDict();
  G__cpp_setup_globalCalibHeaderDict();
  G__cpp_setup_funcCalibHeaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCalibHeaderDict();
  return;
}
class G__cpp_setup_initCalibHeaderDict {
  public:
    G__cpp_setup_initCalibHeaderDict() { G__add_setup_func("CalibHeaderDict",(G__incsetup)(&G__cpp_setupCalibHeaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCalibHeaderDict() { G__remove_setup_func("CalibHeaderDict"); }
};
G__cpp_setup_initCalibHeaderDict G__cpp_setup_initializerCalibHeaderDict;

