/********************************************************************
* ../src/CalibTTChannelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/CalibTTChannelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCalibTTChannelDict();
extern void G__cpp_setup_inheritanceCalibTTChannelDict();
extern void G__cpp_setup_typetableCalibTTChannelDict();
extern void G__cpp_setup_memvarCalibTTChannelDict();
extern void G__cpp_setup_globalCalibTTChannelDict();
extern void G__cpp_setup_memfuncCalibTTChannelDict();
extern void G__cpp_setup_funcCalibTTChannelDict();
extern void G__set_cpp_environmentCalibTTChannelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CalibTTChannel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CalibTTChannelDictLN_TClass;
extern G__linked_taginfo G__CalibTTChannelDictLN_TBuffer;
extern G__linked_taginfo G__CalibTTChannelDictLN_TMemberInspector;
extern G__linked_taginfo G__CalibTTChannelDictLN_TObject;
extern G__linked_taginfo G__CalibTTChannelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CalibTTChannelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibTTChannelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CalibTTChannelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibTTChannelDictLN_JM;
extern G__linked_taginfo G__CalibTTChannelDictLN_JMcLcLCalibTTChannel;

/* STUB derived class for protected member access */
