/********************************************************************
* ../src/ElecFeeChannelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/ElecFeeChannelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableElecFeeChannelDict();
extern void G__cpp_setup_inheritanceElecFeeChannelDict();
extern void G__cpp_setup_typetableElecFeeChannelDict();
extern void G__cpp_setup_memvarElecFeeChannelDict();
extern void G__cpp_setup_globalElecFeeChannelDict();
extern void G__cpp_setup_memfuncElecFeeChannelDict();
extern void G__cpp_setup_funcElecFeeChannelDict();
extern void G__set_cpp_environmentElecFeeChannelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ElecFeeChannel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ElecFeeChannelDictLN_TClass;
extern G__linked_taginfo G__ElecFeeChannelDictLN_TBuffer;
extern G__linked_taginfo G__ElecFeeChannelDictLN_TMemberInspector;
extern G__linked_taginfo G__ElecFeeChannelDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ElecFeeChannelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ElecFeeChannelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecFeeChannelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ElecFeeChannelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecFeeChannelDictLN_JM;
extern G__linked_taginfo G__ElecFeeChannelDictLN_JMcLcLElecFeeChannel;

/* STUB derived class for protected member access */
