/********************************************************************
* ../src/ElecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/ElecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableElecEventDict();
extern void G__cpp_setup_inheritanceElecEventDict();
extern void G__cpp_setup_typetableElecEventDict();
extern void G__cpp_setup_memvarElecEventDict();
extern void G__cpp_setup_globalElecEventDict();
extern void G__cpp_setup_memfuncElecEventDict();
extern void G__cpp_setup_funcElecEventDict();
extern void G__set_cpp_environmentElecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ElecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ElecEventDictLN_TClass;
extern G__linked_taginfo G__ElecEventDictLN_TBuffer;
extern G__linked_taginfo G__ElecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__ElecEventDictLN_TObject;
extern G__linked_taginfo G__ElecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ElecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ElecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecEventDictLN_JM;
extern G__linked_taginfo G__ElecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__ElecEventDictLN_JMcLcLElecFeeCrate;
extern G__linked_taginfo G__ElecEventDictLN_maplEintcOJMcLcLElecFeeChannelcOlesslEintgRcOallocatorlEpairlEconstsPintcOJMcLcLElecFeeChannelgRsPgRsPgR;
extern G__linked_taginfo G__ElecEventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ElecEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecEventDictLN_JMcLcLElecEvent;

/* STUB derived class for protected member access */
