/********************************************************************
* ../src/ElecHeaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/ElecHeaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableElecHeaderDict();
extern void G__cpp_setup_inheritanceElecHeaderDict();
extern void G__cpp_setup_typetableElecHeaderDict();
extern void G__cpp_setup_memvarElecHeaderDict();
extern void G__cpp_setup_globalElecHeaderDict();
extern void G__cpp_setup_memfuncElecHeaderDict();
extern void G__cpp_setup_funcElecHeaderDict();
extern void G__set_cpp_environmentElecHeaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ElecHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ElecHeaderDictLN_TClass;
extern G__linked_taginfo G__ElecHeaderDictLN_TBuffer;
extern G__linked_taginfo G__ElecHeaderDictLN_TMemberInspector;
extern G__linked_taginfo G__ElecHeaderDictLN_TObject;
extern G__linked_taginfo G__ElecHeaderDictLN_string;
extern G__linked_taginfo G__ElecHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ElecHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ElecHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecHeaderDictLN_JM;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLHeaderObject;
extern G__linked_taginfo G__ElecHeaderDictLN_maplEintcOJMcLcLElecFeeChannelcOlesslEintgRcOallocatorlEpairlEconstsPintcOJMcLcLElecFeeChannelgRsPgRsPgR;
extern G__linked_taginfo G__ElecHeaderDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ElecHeaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLElecEvent;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLSpmtElecEvent;
extern G__linked_taginfo G__ElecHeaderDictLN_vectorlEJMcLcLSpmtElecAbcBlockcOallocatorlEJMcLcLSpmtElecAbcBlockgRsPgR;
extern G__linked_taginfo G__ElecHeaderDictLN_reverse_iteratorlEvectorlEJMcLcLSpmtElecAbcBlockcOallocatorlEJMcLcLSpmtElecAbcBlockgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLSmartRef;
extern G__linked_taginfo G__ElecHeaderDictLN_JMcLcLElecHeader;

/* STUB derived class for protected member access */
