/********************************************************************
* ../src/SpmtElecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/SpmtElecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSpmtElecEventDict();
extern void G__cpp_setup_inheritanceSpmtElecEventDict();
extern void G__cpp_setup_typetableSpmtElecEventDict();
extern void G__cpp_setup_memvarSpmtElecEventDict();
extern void G__cpp_setup_globalSpmtElecEventDict();
extern void G__cpp_setup_memfuncSpmtElecEventDict();
extern void G__cpp_setup_funcSpmtElecEventDict();
extern void G__set_cpp_environmentSpmtElecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SpmtElecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SpmtElecEventDictLN_TClass;
extern G__linked_taginfo G__SpmtElecEventDictLN_TBuffer;
extern G__linked_taginfo G__SpmtElecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__SpmtElecEventDictLN_TObject;
extern G__linked_taginfo G__SpmtElecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SpmtElecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SpmtElecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SpmtElecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SpmtElecEventDictLN_JM;
extern G__linked_taginfo G__SpmtElecEventDictLN_JMcLcLEventObject;
extern G__linked_taginfo G__SpmtElecEventDictLN_JMcLcLSpmtElecEvent;
extern G__linked_taginfo G__SpmtElecEventDictLN_vectorlEJMcLcLSpmtElecAbcBlockcOallocatorlEJMcLcLSpmtElecAbcBlockgRsPgR;
extern G__linked_taginfo G__SpmtElecEventDictLN_reverse_iteratorlEvectorlEJMcLcLSpmtElecAbcBlockcOallocatorlEJMcLcLSpmtElecAbcBlockgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
