/********************************************************************
* ../src/EvtNavigatorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/EvtNavigatorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEvtNavigatorDict();
extern void G__cpp_setup_inheritanceEvtNavigatorDict();
extern void G__cpp_setup_typetableEvtNavigatorDict();
extern void G__cpp_setup_memvarEvtNavigatorDict();
extern void G__cpp_setup_globalEvtNavigatorDict();
extern void G__cpp_setup_memfuncEvtNavigatorDict();
extern void G__cpp_setup_funcEvtNavigatorDict();
extern void G__set_cpp_environmentEvtNavigatorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EvtNavigator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EvtNavigatorDictLN_TClass;
extern G__linked_taginfo G__EvtNavigatorDictLN_TBuffer;
extern G__linked_taginfo G__EvtNavigatorDictLN_TMemberInspector;
extern G__linked_taginfo G__EvtNavigatorDictLN_TObject;
extern G__linked_taginfo G__EvtNavigatorDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_string;
extern G__linked_taginfo G__EvtNavigatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_TTimeStamp;
extern G__linked_taginfo G__EvtNavigatorDictLN_JM;
extern G__linked_taginfo G__EvtNavigatorDictLN_JMcLcLSmartRef;
extern G__linked_taginfo G__EvtNavigatorDictLN_JMcLcLHeaderObject;
extern G__linked_taginfo G__EvtNavigatorDictLN_JMcLcLEvtNavigator;
extern G__linked_taginfo G__EvtNavigatorDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_vectorlEJMcLcLSmartRefmUcOallocatorlEJMcLcLSmartRefmUgRsPgR;
extern G__linked_taginfo G__EvtNavigatorDictLN_reverse_iteratorlEvectorlEJMcLcLSmartRefmUcOallocatorlEJMcLcLSmartRefmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
