/********************************************************************
* ../src/testDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/testDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabletestDict();
extern void G__cpp_setup_inheritancetestDict();
extern void G__cpp_setup_typetabletestDict();
extern void G__cpp_setup_memvartestDict();
extern void G__cpp_setup_globaltestDict();
extern void G__cpp_setup_memfunctestDict();
extern void G__cpp_setup_functestDict();
extern void G__set_cpp_environmenttestDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "test.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__testDictLN_TClass;
extern G__linked_taginfo G__testDictLN_TBuffer;
extern G__linked_taginfo G__testDictLN_TMemberInspector;
extern G__linked_taginfo G__testDictLN_TObject;
extern G__linked_taginfo G__testDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__testDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__testDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__testDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__testDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__testDictLN_DBITableRow;
extern G__linked_taginfo G__testDictLN_test;

/* STUB derived class for protected member access */
